# -*- coding: utf-8 -*-
"""conftest

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gh6LSzdtL8YQcRHjq5z_jY5e3DW1mEO3
"""

# tests/conftest.py
import sys
from pathlib import Path

# Resolve project root: .../chemsuite-v1.0.x
ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))