# -*- coding: utf-8 -*-
"""ea_integration_test

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yj1S23Zg5qggAnp_Xy3o9tHJrdmC-Sp1
"""

import pytest

from logic import parse_chemical_formula, calculate_elemental_composition, merge_formulas
from logic.ea import find_best_fit


def test_ea_recovers_known_coefficients():
    base = parse_chemical_formula("C10H22N2O")
    h2o = parse_chemical_formula("H2O")
    meoh = parse_chemical_formula("CH4O")

    # Build experimental composition
    combined = merge_formulas(base, (h2o, 0.25), (meoh, 0.50))
    experimental = calculate_elemental_composition(combined)

    solvents = [
        (h2o, 0.0, 1.0, "H2O"),
        (meoh, 0.0, 1.0, "MeOH"),
    ]

    result = find_best_fit(
        main_counts=base,
        experimental=experimental,
        solvents=solvents,
        increment=0.25,
        tolerance=0.4,
    )

    assert result["max_diff"] == pytest.approx(0.0, abs=1e-9)
    assert ("H2O", 0.25) in result["solvents_used"]
    assert ("MeOH", 0.50) in result["solvents_used"]