# -*- coding: utf-8 -*-
"""logic_formula_test

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mLerq0DTvy5zfvWSeh9G4ApYS9nXg9I6
"""

import pytest

from logic import (
    parse_chemical_formula,
    calculate_molecular_weight,
    calculate_elemental_composition,
    merge_formulas,
    format_chemical_formula_html,
)


def test_parse_simple_and_parenthesized_formulas():
    # Simple
    counts = parse_chemical_formula("C6H6")
    assert counts == {"C": 6, "H": 6}

    # Parentheses multiplier: C2H5(OH)2 -> C2 H7 O2
    counts = parse_chemical_formula("C2H5(OH)2")
    assert counts == {"C": 2, "H": 7, "O": 2}

    # Nested group example: CH3(CH2)3CH3 -> C5 H12
    counts = parse_chemical_formula("CH3(CH2)3CH3")
    assert counts == {"C": 5, "H": 12}

    # Unmatched closing parenthesis should raise
    with pytest.raises(ValueError):
        parse_chemical_formula("C6H6)")


def test_calculate_molecular_weight_and_composition_reasonable():
    # Glucose: C6H12O6
    counts = parse_chemical_formula("C6H12O6")
    mw = calculate_molecular_weight(counts)
    assert mw > 0.0

    comp = calculate_elemental_composition(counts)
    # Rough expected percentages (using lib.atomic_data values):
    # C ~ 40%, H ~ 6-7%, O ~ 53%
    assert comp["C"] == pytest.approx(40.0, abs=1.0)
    assert comp["H"] == pytest.approx(6.7, abs=0.5)
    assert comp["O"] == pytest.approx(53.3, abs=1.0)
    assert sum(comp.values()) == pytest.approx(100.0, abs=0.05)


def test_merge_formulas_supports_fractional_equivalents():
    main = parse_chemical_formula("C10H22N2O")
    h2o = parse_chemical_formula("H2O")
    meoh = parse_chemical_formula("CH4O")

    merged = merge_formulas(main, (h2o, 0.25), (meoh, 0.50))
    # Spot-check a few elements (floats allowed)
    assert merged["O"] == pytest.approx(main["O"] + 0.25 * h2o["O"] + 0.50 * meoh["O"])
    assert merged["H"] == pytest.approx(main["H"] + 0.25 * h2o["H"] + 0.50 * meoh["H"])


def test_format_chemical_formula_html_subscripts():
    s = "C6H12O6"
    html = format_chemical_formula_html(s)
    assert "C<sub>6</sub>H<sub>12</sub>O<sub>6"