# -*- coding: utf-8 -*-
"""ms_data_test

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mrzTgqheZWXsqBzOU9XKJJzPqcttkGYs
"""

import pytest

from lib import ms_adducts_data
from lib.ms_isotopes_data import ISOTOPE_DATA


def test_electron_mass_positive():
    # Electron mass constant must be positive
    me = ms_adducts_data.ELECTRON_MASS
    assert me > 0.0  # basic sanity
    # Spot-check magnitude (roughly ~5.4858e-4 u) but avoid over-constraining.
    assert 5e-4 < me < 6e-4


def test_mass_offset_signs_match_mode():
    """
    In your data:
      - Positive mode: mass_offset = -ELECTRON_MASS  (electron removed)
      - Negative mode: mass_offset = +ELECTRON_MASS  (electron added)
    """
    pos = ms_adducts_data.ADDUCTS["positive"]
    neg = ms_adducts_data.ADDUCTS["negative"]

    # Positive mode adducts -> negative offsets
    for key in ["[M]+", "[M+H]+", "[M+Na]+", "[M+NH4]+", "[M+K]+"]:
        assert key in pos, f"Missing positive adduct: {key}"
        assert pos[key]["mass_offset"] < 0.0, f"{key} must have negative mass_offset"

    # Negative mode adducts -> positive offsets
    for key in ["[M]-", "[M-H]-", "[M+Cl]-", "[M+HCO2]-", "[M+CH3CO2]-", "[M+Br]-", "[M+CF3CO2]-"]:
        assert key in neg, f"Missing negative adduct: {key}"
        assert neg[key]["mass_offset"] > 0.0, f"{key} must have positive mass_offset"


def test_adduct_schema_and_charge_consistency():
    """
    Verify each adduct dict contains required fields and charges are consistent
    with mode: +1 for positive mode, -1 for negative mode.
    """
    required_keys = {"name", "add", "sub", "charge", "mass_offset"}

    for mode, table in ms_adducts_data.ADDUCTS.items():
        for name, ad in table.items():
            # Schema presence
            missing = required_keys - set(ad.keys())
            assert not missing, f"Adduct {name} missing keys: {missing}"

            # Charge consistency
            if mode == "positive":
                assert ad["charge"] == 1, f"{name}: positive-mode charge must be +1"
            else:
                assert ad["charge"] == -1, f"{name}: negative-mode charge must be -1"

            # Types basic sanity
            assert isinstance(ad["add"], dict)
            assert isinstance(ad["sub"], dict)
            assert isinstance(ad["mass_offset"], (float, int))


@pytest.mark.parametrize("element", ["C", "Cl", "Na", "H", "O"])
def test_isotope_table_integrity_for_common_elements(element):
    """
    For selected elements:
      - payload is a dict of mass_number -> {mass, abundance}
      - mass > 0, abundance in [0, 1]
      - total abundances per element sum ~ 1.0 (fractional form)
    """
    assert element in ISOTOPE_DATA
    payload = ISOTOPE_DATA[element]
    assert isinstance(payload, dict) and len(payload) >= 1

    total_abund = 0.0
    for mass_num, rec in payload.items():
        assert "mass" in rec and "abundance" in rec, f"{element} isotope {mass_num} missing fields"
        assert rec["mass"] > 0.0, f"{element} isotope {mass_num} mass must be positive"
        # Your table uses fractional abundances (0..1)
        assert 0.0 <= rec["abundance"] <= 1.0, f"{element} isotope {mass_num} abundance out of [0,1]"
        total_abund += rec["abundance"]

    # Allow a small tolerance for rounding differences