# -*- coding: utf-8 -*-
"""nmr_test

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14UkZqxF-PqOz_dJUvmg-ORfBZe_IvpfK
"""

import pytest
import unittest

# Prefer public API; fallback if not re-exported
try:
    from logic import (
        format_notes_richtext_html,
        format_nmr_coupling_html,
        format_chemical_inline_html,
    )
except Exception:
    from logic.logic import (
        format_notes_richtext_html,
        format_nmr_coupling_html,
        format_chemical_inline_html,
    )

# Optional Qt imports for widget tests
try:
    from PyQt6.QtWidgets import QApplication, QHeaderView
    from nmr_impurities import NMRImpuritiesWidget
    HAVE_QT6 = True
except Exception:
    HAVE_QT6 = False

class TestFormattingFunctions(unittest.TestCase):
    def test_inline_chemical_embedded_digits(self):
        self.assertEqual(format_chemical_inline_html("CD3CN"), "CD<sub>3</sub>CN")
    def test_inline_isotopic_label_d8(self):
        self.assertEqual(format_chemical_inline_html("THF-d8"), "THF-d<sub>8</sub>")
    def test_group_multiplier_after_paren(self):
        formatted = format_chemical_inline_html("(CD3)2SO")
        self.assertIn("(CD<sub>3</sub>)", formatted)
        self.assertIn(")<sub>2</sub>SO", formatted)
    def test_group_multiplier_token_end(self):
        self.assertEqual(format_chemical_inline_html("(CH2)4"),
                         "(CH<sub>2</sub>)<sub>4</sub>")
    def test_nmr_coupling_formats(self):
        self.assertEqual(format_nmr_coupling_html("2JH,D = 1 Hz"),
                         "<sup>2</sup><i>J</i><sub>H,D</sub> = 1 Hz")
        self.assertEqual(format_nmr_coupling_html("J = 5.5 Hz"),
                         "<i>J</i> = 5.5 Hz")
        self.assertEqual(format_nmr_coupling_html("(2JP,C = 3 Hz)"),
                         "(<sup>2</sup><i>J</i><sub>P,C</sub> = 3 Hz)")
    def test_notes_richtext_pipeline(self):
        text = ("Asignal for HDO is also observed in (CD3)2SO (3.30 ppm) and "
                "(CD3)2CO (2.81 ppm), often seen as a 1:1:1 triplet (2JH, D = 1 Hz).")
        html = format_notes_richtext_html(text)
        self.assertIn("(CD<sub>3</sub>)<sub>2</sub>SO", html)
        self.assertIn("(CD<sub>3</sub>)<sub>2</sub>CO", html)
        self.assertIn("(<sup>2</sup><i>J</i><sub>H,D</sub> = 1 Hz)", html)
        self.assertIn("1:1:1", html)

@unittest.skipUnless(HAVE_QT6, "PyQt6 not available; skipping widget tests")
class TestNMRImpuritiesWidget(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls._app = QApplication.instance() or QApplication([])
    def setUp(self):
        self.w = NMRImpuritiesWidget()
    def tearDown(self):
        self.w.deleteLater()
    def test_initial_1h_columns_and_header_modes(self):
        self.assertTrue(self.w.rad_1h.isChecked())
        self.assertEqual(self.w.tree.columnCount(), 6)
        self.assertFalse(self.w.tree.header().stretchLastSection())
        ref_idx = self.w._find_column("Ref")
        self.assertIsNotNone(ref_idx)
        self.assertEqual(self.w.tree.header().sectionResizeMode(ref_idx),
                         QHeaderView.ResizeMode.Fixed)
        self.assertEqual(self.w.tree.header().sectionResizeMode(0),
                         QHeaderView.ResizeMode.Interactive)
    def test_switch_to_13c_columns(self):
        self.w.rad_13c.setChecked(True)
        self.assertEqual(self.w.tree.columnCount(), 5)
        ref_idx = self.w._find_column("Ref")
        self.assertIsNotNone(ref_idx)
        self.assertEqual(self.w.tree.header().sectionResizeMode(ref_idx),
                         QHeaderView.ResizeMode.Fixed)
    def test_solvent_selection_populates_and_refs_box(self):
        combo = self.w.solvent_combo
        self.assertGreater(combo.count(), 0)
        idx = 1 if combo.count() > 1 else 0
        combo.setCurrentIndex(idx)
        self.assertGreater(self.w.tree.topLevelItemCount(), 0)
        html = self.w.ref_text.toHtml()
        self.assertIn("Notes:", html)
        self.assertIn("References:", html)

    if __name__ == "__main__":

        unittest.main()