# -*- coding: utf-8 -*-
"""shared_functions_test

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pW4b3oIYPl3c9EyRrxmHb3Z4xGlb0wgz
"""

import os
import io

from logic.shared_functions import ensure_instruction_page


def test_ensure_instruction_page_creates_file(tmp_path):
    instructions_dir = tmp_path / "instructions"
    filename = "test_widget_inst.html"
    title = "Test Widget"

    ensure_instruction_page(str(instructions_dir), filename, title)
    path = instructions_dir / filename
    assert path.exists()

    html = path.read_text(encoding="utf-8")
    assert title in html
    assert "<!DOCTYPE html>" in html
    assert "<html" in html


def test_ensure_instruction_page_is_idempotent(tmp_path):
    instructions_dir = tmp_path / "instructions"
    filename = "test_widget_inst.html"
    title = "Test Widget"

    ensure_instruction_page(str(instructions_dir), filename, title)
    path = instructions_dir / filename
    original = path.read_text(encoding="utf-8")

    # Simulate user editing the file
    path.write_text(original + "\n<!-- custom content -->\n", encoding="utf-8")

    # Re-invoke: should NOT overwrite
    ensure_instruction_page(str(instructions_dir), filename, title)
    after = path.read_text(encoding="utf-8")