# -*- coding: utf-8 -*-
"""viscosity_test

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IcEXk_LK-vrGGvaUpwU5JAkqgep6KI5l
"""

import pytest

from logic.viscosity import viscosity_and_solvent_mw


def test_direct_entry_positive_values_toluene_d8():
    T = 298.15
    eta, mw = viscosity_and_solvent_mw("Toluene-d8", T)
    assert eta is not None and mw is not None
    assert eta > 0.0
    assert mw > 0.0


def test_direct_entry_temperature_monotonicity():
    solvent = "Chloroform-d"
    T_low, T_high = 278.15, 318.15  # 5°C vs 45°C approx
    eta_low, _ = viscosity_and_solvent_mw(solvent, T_low)
    eta_high, _ = viscosity_and_solvent_mw(solvent, T_high)
    assert eta_low is not None and eta_high is not None
    # exp(b/T): higher T => smaller b/T => smaller exp(...) => smaller viscosity
    assert eta_high < eta_low


def test_inferred_entry_ethanol_d6():
    T = 298.15
    eta, mw = viscosity_and_solvent_mw("Ethanol-d6", T)
    assert eta is not None and mw is not None
    assert eta > 0.0
    assert mw > 0.0


def test_unknown_and_custom_return_none():
    T = 298.15
    eta, mw = viscosity_and_solvent_mw("Not-A-Real-Solvent", T)
    assert eta is None and mw is None

    eta, mw = viscosity_and_solvent_mw("Custom", T)