# -*- coding: utf-8 -*-
"""dil_calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lJkJWqqhzsHg-jzS6YBym7bCeZGKny-j
"""

import re
from PyQt6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QLabel, QLineEdit,
    QDoubleSpinBox, QComboBox, QPushButton, QTextEdit,
    QGroupBox, QScrollArea, QFrame, QGridLayout
)
from PyQt6.QtCore import Qt

from logic.shared_functions import BaseWidget
from logic import (
    parse_chemical_formula, calculate_molecular_weight, format_chemical_formula_html,
    volume_of_stock_L, mass_for_solution_g, stock_molarity_from_density_M
)
from lib.common_reagents_data import COMMON_REAGENTS


class DilutionCalculator(BaseWidget):
    # Standardised help key so F1 resolves to instructions/dil_calculator_inst.html
    help_key = "dil_calculator"

    def __init__(self):
        super().__init__()
        self.init_ui()

    def init_ui(self):
        # Main scroll container
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)

        content_widget = QWidget()
        scroll.setWidget(content_widget)

        main_layout = QVBoxLayout(content_widget)
        main_layout.setSpacing(20)

        LABEL_MIN_WIDTH = 170

        # --- 1. Solution Dilution Calculator (C1V1 = C2V2) ---
        dilution_group = QGroupBox("1. Solution Dilution Calculator")
        dil_grid = QGridLayout()
        dil_grid.setColumnMinimumWidth(0, LABEL_MIN_WIDTH)

        dil_grid.addWidget(QLabel("Stock Concentration:"), 0, 0)
        self.dil_c1_spin = QDoubleSpinBox()
        self.dil_c1_spin.setRange(0, 999999)
        self.dil_c1_spin.setValue(10)
        dil_grid.addWidget(self.dil_c1_spin, 0, 1)

        self.dil_c1_unit = QComboBox()
        self.dil_c1_unit.addItems(["M", "mM", "µM", "nM"])
        self.dil_c1_unit.setCurrentText("mM")
        dil_grid.addWidget(self.dil_c1_unit, 0, 2)

        dil_grid.addWidget(QLabel("Final Volume:"), 1, 0)
        self.dil_v2_spin = QDoubleSpinBox()
        self.dil_v2_spin.setRange(0, 999999)
        self.dil_v2_spin.setValue(10)
        dil_grid.addWidget(self.dil_v2_spin, 1, 1)

        self.dil_v2_unit = QComboBox()
        self.dil_v2_unit.addItems(["L", "mL", "µL"])
        self.dil_v2_unit.setCurrentText("mL")
        dil_grid.addWidget(self.dil_v2_unit, 1, 2)

        dil_grid.addWidget(QLabel("Final Concentration:"), 2, 0)
        self.dil_c2_spin = QDoubleSpinBox()
        self.dil_c2_spin.setRange(0, 999999)
        self.dil_c2_spin.setValue(1)
        dil_grid.addWidget(self.dil_c2_spin, 2, 1)

        self.dil_c2_unit = QComboBox()
        self.dil_c2_unit.addItems(["M", "mM", "µM", "nM"])
        self.dil_c2_unit.setCurrentText("mM")
        dil_grid.addWidget(self.dil_c2_unit, 2, 2)

        dil_grid.setColumnStretch(3, 1)
        self.dil_calc_btn = QPushButton("Calculate")
        self.dil_calc_btn.setStyleSheet("background-color: #3498db; color: white; font-weight: bold;")
        self.dil_calc_btn.clicked.connect(self.calculate_simple_dilution)
        dil_grid.addWidget(self.dil_calc_btn, 3, 0, 1, 4)

        self.dil_result = QTextEdit()
        self.dil_result.setReadOnly(True)
        self.dil_result.setMaximumHeight(60)
        dil_grid.addWidget(self.dil_result, 4, 0, 1, 4)

        dilution_group.setLayout(dil_grid)
        main_layout.addWidget(dilution_group)

        # --- 2. Acids & Bases Molarity Calculator ---
        ab_group = QGroupBox("2. Acids && Bases Molarity Calculator")
        ab_grid = QGridLayout()
        ab_grid.setColumnMinimumWidth(0, LABEL_MIN_WIDTH)

        ab_grid.addWidget(QLabel("Reagent:"), 0, 0)
        self.ab_combo = QComboBox()
        self.ab_combo.addItems(sorted(COMMON_REAGENTS.keys()))
        self.ab_combo.currentTextChanged.connect(self.populate_ab_data)
        ab_grid.addWidget(self.ab_combo, 0, 1, 1, 2)

        ab_props = QHBoxLayout()

        # Density
        dens_layout = QHBoxLayout()
        dens_layout.setSpacing(5)
        dens_layout.addWidget(QLabel("Density (g/mL):"))
        self.ab_dens = QDoubleSpinBox()
        self.ab_dens.setDecimals(3)
        self.ab_dens.setRange(0, 100)
        dens_layout.addWidget(self.ab_dens)
        ab_props.addLayout(dens_layout)
        ab_props.addSpacing(20)

        # MW
        mw_layout = QHBoxLayout()
        mw_layout.setSpacing(5)
        mw_layout.addWidget(QLabel("MW (g/mol):"))
        self.ab_mw = QDoubleSpinBox()
        self.ab_mw.setDecimals(2)
        self.ab_mw.setRange(0, 1000)
        mw_layout.addWidget(self.ab_mw)
        ab_props.addLayout(mw_layout)
        ab_props.addSpacing(20)

        # Purity
        purity_layout = QHBoxLayout()
        purity_layout.setSpacing(5)
        purity_layout.addWidget(QLabel("Purity (%):"))
        self.ab_purity = QDoubleSpinBox()
        self.ab_purity.setRange(0, 100)
        purity_layout.addWidget(self.ab_purity)
        ab_props.addLayout(purity_layout)
        ab_props.addStretch()

        ab_grid.addLayout(ab_props, 1, 0, 1, 4)

        ab_grid.addWidget(QLabel("Final Volume:"), 2, 0)
        self.ab_vol_spin = QDoubleSpinBox()
        self.ab_vol_spin.setRange(0, 999999)
        self.ab_vol_spin.setValue(100)
        ab_grid.addWidget(self.ab_vol_spin, 2, 1)

        self.ab_vol_unit = QComboBox()
        self.ab_vol_unit.addItems(["L", "mL", "µL"])
        self.ab_vol_unit.setCurrentText("mL")
        ab_grid.addWidget(self.ab_vol_unit, 2, 2)

        ab_grid.addWidget(QLabel("Final Concentration:"), 3, 0)
        self.ab_conc_spin = QDoubleSpinBox()
        self.ab_conc_spin.setRange(0, 100)
        self.ab_conc_spin.setValue(1)
        ab_grid.addWidget(self.ab_conc_spin, 3, 1)

        self.ab_conc_unit = QComboBox()
        self.ab_conc_unit.addItems(["M", "N"])
        self.ab_conc_unit.setCurrentText("M")
        ab_grid.addWidget(self.ab_conc_unit, 3, 2)

        ab_grid.setColumnStretch(3, 1)
        self.ab_calc_btn = QPushButton("Calculate")
        self.ab_calc_btn.setStyleSheet("background-color: #3498db; color: white; font-weight: bold;")
        self.ab_calc_btn.clicked.connect(self.calculate_ab_dilution)
        ab_grid.addWidget(self.ab_calc_btn, 4, 0, 1, 4)

        self.ab_result = QTextEdit()
        self.ab_result.setReadOnly(True)
        self.ab_result.setMaximumHeight(80)
        ab_grid.addWidget(self.ab_result, 5, 0, 1, 4)

        ab_group.setLayout(ab_grid)
        main_layout.addWidget(ab_group)

        self.ab_combo.setCurrentText("Acetic Acid, Glacial")
        self.populate_ab_data(self.ab_combo.currentText())

        # --- 3. Mass Molarity Calculator ---
        mass_group = QGroupBox("3. Mass Molarity Calculator")
        mass_grid = QGridLayout()
        mass_grid.setColumnMinimumWidth(0, LABEL_MIN_WIDTH)

        mass_grid.addWidget(QLabel("Chemical Formula:"), 0, 0)
        self.mass_formula = QLineEdit()
        self.mass_formula.setPlaceholderText("e.g. MnCl2.4H2O")
        self.mass_formula.textChanged.connect(self.on_mass_formula_change)
        mass_grid.addWidget(self.mass_formula, 0, 1, 1, 2)

        mass_grid.addWidget(QLabel("Formula Weight (g/mol):"), 1, 0)
        self.mass_mw_input = QLineEdit()
        self.mass_mw_input.setPlaceholderText("Enter FW (e.g. 197.91)")
        mass_grid.addWidget(self.mass_mw_input, 1, 1, 1, 2)

        mass_grid.addWidget(QLabel("Final Volume:"), 2, 0)
        self.mass_vol_spin = QDoubleSpinBox()
        self.mass_vol_spin.setRange(0, 999999)
        self.mass_vol_spin.setValue(10)
        mass_grid.addWidget(self.mass_vol_spin, 2, 1)

        self.mass_vol_unit = QComboBox()
        self.mass_vol_unit.addItems(["L", "mL", "µL"])
        self.mass_vol_unit.setCurrentText("mL")
        mass_grid.addWidget(self.mass_vol_unit, 2, 2)

        mass_grid.addWidget(QLabel("Final Concentration:"), 3, 0)
        self.mass_conc_spin = QDoubleSpinBox()
        self.mass_conc_spin.setRange(0, 999999)
        self.mass_conc_spin.setValue(10)
        mass_grid.addWidget(self.mass_conc_spin, 3, 1)

        self.mass_conc_unit = QComboBox()
        self.mass_conc_unit.addItems(["M", "mM", "µM", "nM"])
        self.mass_conc_unit.setCurrentText("mM")
        mass_grid.addWidget(self.mass_conc_unit, 3, 2)

        mass_grid.setColumnStretch(3, 1)
        self.mass_calc_btn = QPushButton("Calculate")
        self.mass_calc_btn.setStyleSheet("background-color: #3498db; color: white; font-weight: bold;")
        self.mass_calc_btn.clicked.connect(self.calculate_mass)
        mass_grid.addWidget(self.mass_calc_btn, 4, 0, 1, 4)

        self.mass_result = QTextEdit()
        self.mass_result.setReadOnly(True)
        self.mass_result.setMaximumHeight(60)
        mass_grid.addWidget(self.mass_result, 5, 0, 1, 4)

        mass_group.setLayout(mass_grid)
        main_layout.addWidget(mass_group)

        # Finish Layout
        main_layout.addStretch()
        outer_layout = QVBoxLayout(self)
        outer_layout.setContentsMargins(0, 0, 0, 0)
        outer_layout.addWidget(scroll)

    # --- Unit helpers ---
    def get_unit_factor_conc(self, unit):
        if unit in ("M", "N"):
            return 1.0
        if unit == "mM":
            return 1e-3
        if unit == "µM":
            return 1e-6
        if unit == "nM":
            return 1e-9
        return 1.0

    def get_unit_factor_vol(self, unit):
        if unit == "L":
            return 1.0
        if unit == "mL":
            return 1e-3
        if unit == "µL":
            return 1e-6
        return 1.0

    # --- Formula/MW helpers ---
    def calculate_mw_from_string(self, formula_str):
        """Parses formula string, handling dots for solvates."""
        if not formula_str:
            return 0.0
        parts = formula_str.split('.')
        total_mw = 0.0
        for part in parts:
            part = part.strip()
            if not part:
                continue
            # Optional leading coefficient: e.g. "4H2O"
            m = re.match(r'^(\d*\.?\d+)?(.*)', part)
            if m:
                coeff_str = m.group(1)
                chem_part = m.group(2)
                coeff = float(coeff_str) if coeff_str else 1.0
                try:
                    counts = parse_chemical_formula(chem_part)
                    mw = calculate_molecular_weight(counts)
                    total_mw += mw * coeff
                except Exception:
                    return 0.0
        return total_mw

    def format_display_formula(self, formula_text):
        """Formats the chemical formula string with HTML subscripts and center dots."""
        if not formula_text:
            return ""
        parts = formula_text.split('.')
        formatted_parts = []
        for part in parts:
            part = part.strip()
            if not part:
                continue
            m = re.match(r'^(\d*\.?\d+)?(.*)', part)
            if m:
                coeff = m.group(1)
                chem = m.group(2)
                fmt_chem = format_chemical_formula_html(chem)
                if coeff:
                    formatted_parts.append(f"{coeff}{fmt_chem}")
                else:
                    formatted_parts.append(fmt_chem)
            else:
                formatted_parts.append(format_chemical_formula_html(part))
        return " · ".join(formatted_parts)

    def format_reagent_name_html(self, name):
        """Subscript numbers if they look like formula fragments in a name."""
        return re.sub(r'([A-Za-z])(\d+)', r'\1<sub>\2</sub>', name)

    # --- Slots ---
    def populate_ab_data(self, reagent_name):
        if reagent_name in COMMON_REAGENTS:
            data = COMMON_REAGENTS[reagent_name]
            density = data['density']
            if density == "na":
                self.ab_dens.setValue(0.0)
                self.ab_dens.setEnabled(False)
            else:
                self.ab_dens.setValue(float(density))
                self.ab_dens.setEnabled(True)
            self.ab_mw.setValue(data['mw'])
            self.ab_purity.setValue(data['purity'])

    def calculate_simple_dilution(self):
        c1 = self.dil_c1_spin.value() * self.get_unit_factor_conc(self.dil_c1_unit.currentText())
        v2 = self.dil_v2_spin.value() * self.get_unit_factor_vol(self.dil_v2_unit.currentText())
        c2 = self.dil_c2_spin.value() * self.get_unit_factor_conc(self.dil_c2_unit.currentText())
        try:
            v1_liters = volume_of_stock_L(c1, c2, v2)
        except ValueError as e:
            self.dil_result.setText(f"Error: {e}")
            return

        # Display-friendly units
        if v1_liters < 1e-6:
            val = v1_liters * 1e9
            unit = "nL"
        elif v1_liters < 1e-3:
            val = v1_liters * 1e6
            unit = "µL"
        elif v1_liters < 1:
            val = v1_liters * 1e3
            unit = "mL"
        else:
            val = v1_liters
            unit = "L"

        target_vol_display = self.dil_v2_spin.value()
        target_unit_display = self.dil_v2_unit.currentText()
        text = (
            f"Add <b>{val:.3f} {unit}</b> of your stock solution into a container "
            f"and fill up to <b>{target_vol_display} {target_unit_display}</b> with solvent."
        )
        self.dil_result.setHtml(text)

    def calculate_ab_dilution(self):
        reagent_name = self.ab_combo.currentText()
        if reagent_name not in COMMON_REAGENTS:
            return

        data = COMMON_REAGENTS[reagent_name]
        is_solid = data.get('state') == 'solid'

        mw = self.ab_mw.value()  # g/mol
        purity = self.ab_purity.value() / 100.0  # fraction
        target_vol_l = self.ab_vol_spin.value() * self.get_unit_factor_vol(self.ab_vol_unit.currentText())
        target_conc_m = self.ab_conc_spin.value() * self.get_unit_factor_conc(self.ab_conc_unit.currentText())

        formatted_name = self.format_reagent_name_html(reagent_name)
        target_vol_display = self.ab_vol_spin.value()
        target_unit_display = self.ab_vol_unit.currentText()

        if mw <= 0:
            self.ab_result.setText("Error: MW must be > 0")
            return

        result_html = ""
        if is_solid:
            try:
                # Adjust for purity (% w/w of active)
                pure_mass_g = mass_for_solution_g(mw, target_conc_m, target_vol_l)
                mass_g = pure_mass_g / (purity if purity > 0 else 1.0)
            except ValueError as e:
                self.ab_result.setText(f"Error: {e}")
                return

            if mass_g < 1e-3:
                val = mass_g * 1e6
                unit = "µg"
            elif mass_g < 1:
                val = mass_g * 1e3
                unit = "mg"
            else:
                val = mass_g
                unit = "g"

            result_html = (
                f"Add <b>{val:.3f} {unit}</b> of {formatted_name} and dissolve to a final volume of "
                f"<b>{target_vol_display} {target_unit_display}</b>."
            )
        else:
            density = self.ab_dens.value()  # g/mL
            try:
                molarity_stock = stock_molarity_from_density_M(density, purity, mw)
            except ValueError as e:
                self.ab_result.setText(f"Error: {e}")
                return

            v1_liters = volume_of_stock_L(molarity_stock, target_conc_m, target_vol_l)
            if v1_liters < 1e-3:
                val = v1_liters * 1e6
                unit = "µL"
            elif v1_liters < 1:
                val = v1_liters * 1e3
                unit = "mL"
            else:
                val = v1_liters
                unit = "L"

            result_html = (
                f"Stock Concentration is approx. <b>{molarity_stock:.2f} M</b>.<br>"
                f"Add <b>{val:.3f} {unit}</b> of {formatted_name} and make it to "
                f"<b>{target_vol_display} {target_unit_display}</b>."
            )

        r_type = data.get('type', 'acid').lower()
        caution_text = (
            f"<br><span style='color:red; font-weight:bold;'>Caution! Always add {r_type} slowly to water.</span>"
        )
        result_html += caution_text
        self.ab_result.setHtml(result_html)

    def on_mass_formula_change(self, text):
        mw = self.calculate_mw_from_string(text)
        if mw > 0:
            self.mass_mw_input.setText(f"{mw:.2f}")

    def calculate_mass(self):
        try:
            mw = float(self.mass_mw_input.text().strip())
        except ValueError:
            mw = 0.0
        if mw <= 0:
            self.mass_result.setText("Error: MW must be valid and > 0.")
            return

        vol = self.mass_vol_spin.value() * self.get_unit_factor_vol(self.mass_vol_unit.currentText())  # L
        conc = self.mass_conc_spin.value() * self.get_unit_factor_conc(self.mass_conc_unit.currentText())  # M
        try:
            mass_g = mass_for_solution_g(mw, conc, vol)
        except ValueError as e:
            self.mass_result.setText(f"Error: {e}")
            return

        if mass_g < 1e-3:
            val = mass_g * 1e6
            unit = "µg"
        elif mass_g < 1:
            val = mass_g * 1e3
            unit = "mg"
        else:
            val = mass_g
            unit = "g"

        target_vol_display = self.mass_vol_spin.value()
        target_unit_display = self.mass_vol_unit.currentText()

        formula_text = self.mass_formula.text().strip()
        if formula_text:
            formatted_subject = self.format_display_formula(formula_text)
        else:
            formatted_subject = "your sample"

        text = (
            f"Add <b>{val:.3f} {unit}</b> of {formatted_subject} and dissolve to a final volume of "
            f"<b>{target_vol_display} {target_unit_display}</b>."
        )
        self.mass_result.setHtml(text)

    # --- Copy & clear helpers (Edit menu compatibility) ---
    def copy_results(self):
        # Concatenate outputs into a single text blob for clipboard
        text = []
        if self.dil_result.toPlainText():
                       text.append("[Dilution]\n" + self.dil_result.toPlainText())
        if self.ab_result.toPlainText():
            text.append("[Acids/Bases]\n" + self.ab_result.toPlainText())
        if self.mass_result.toPlainText():
            text.append("[Mass]\n" + self.mass_result.toPlainText())
        self.copy_text("\n\n".join(text))

    def clear_inputs(self):
        # Dilution
        self.dil_c1_spin.setValue(10)
        self.dil_v2_spin.setValue(10)
        self.dil_c2_spin.setValue(1)
        self.dil_result.clear()
        # Acids & Bases
        self.ab_vol_spin.setValue(100)
        self.ab_conc_spin.setValue(1)
        self.ab_result.clear()
        self.ab_combo.setCurrentText("Acetic Acid, Glacial")
        self.populate_ab_data(self.ab_combo.currentText())
        # Mass
        self.mass_formula.clear()
        self.mass_mw_input.clear()
        self.mass_vol_spin.setValue(10)
        self.mass_conc_spin.setValue(10)
        self.mass_result.clear()