# -*- coding: utf-8 -*-
"""dosy_calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fAIUIyReyToB846ZSpvLDDYLLyr0a0wH
"""

import math
from PyQt6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QLabel, QLineEdit,
    QComboBox, QPushButton, QGroupBox, QRadioButton, QButtonGroup,
    QFormLayout, QStackedWidget, QSlider
)
from PyQt6.QtCore import Qt
from PyQt6.QtGui import QDoubleValidator, QFont

from logic.shared_functions import BaseWidget
from logic import (
    viscosity_and_solvent_mw,
    se_rh_from_D, se_D_from_rh,
    segwe_D, segwe_estimate_MW_from_D,
    PI, NA, RHO_EFF  # constants for the rH→MW branch
)


class DOSYCalculator(BaseWidget):
    # Standardised help key so F1 resolves to instructions/dosy_calculator_inst.html
    help_key = "dosy_calculator"

    def __init__(self, parent=None):
        super().__init__(parent)
        self.init_ui()

    def init_ui(self):
        layout = QVBoxLayout()
        layout.setContentsMargins(10, 10, 10, 10)

        # Title
        title = QLabel("DOSY NMR Calculator")
        font = title.font()
        font.setPointSize(16)
        font.setBold(True)
        title.setFont(font)
        title.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(title)

        # Method selection
        method_group = QGroupBox("Calculation Method")
        method_layout = QVBoxLayout()
        self.method_combo = QComboBox()
        self.method_combo.addItems(["Stokes-Einstein Equation", "SEGWE Method"])
        self.method_combo.currentIndexChanged.connect(self.toggle_method_ui)
        method_layout.addWidget(self.method_combo)
        method_group.setLayout(method_layout)
        layout.addWidget(method_group)

        # Pages stack
        self.stack = QStackedWidget()

        # Page 1: Stokes–Einstein
        self.page_se = QWidget()
        self.init_stokes_einstein_ui()
        self.stack.addWidget(self.page_se)

        # Page 2: SEGWE
        self.page_segwe = QWidget()
        self.init_segwe_ui()
        self.stack.addWidget(self.page_segwe)

        layout.addWidget(self.stack)

        # Shared report area
        rep_group = QGroupBox("Report")
        rep_layout = QVBoxLayout()
        self.report_field = QLineEdit()
        self.report_field.setPlaceholderText("Report string will appear here...")
        self.report_field.setReadOnly(True)
        rep_layout.addWidget(self.report_field)
        rep_group.setLayout(rep_layout)
        layout.addWidget(rep_group)

        # Shared action buttons
        btn_layout = QHBoxLayout()
        self.btn_copy_res = QPushButton("Copy Results")
        self.btn_copy_res.clicked.connect(self.copy_results)
        self.btn_copy_rep = QPushButton("Copy Report")
        self.btn_copy_rep.clicked.connect(self.copy_report)
        btn_layout.addWidget(self.btn_copy_res)
        btn_layout.addWidget(self.btn_copy_rep)
        layout.addLayout(btn_layout)

        self.setLayout(layout)
        self.toggle_method_ui(0)

    # ---------------- Stokes–Einstein UI & Logic ----------------
    def init_stokes_einstein_ui(self):
        layout = QVBoxLayout(self.page_se)
        layout.setContentsMargins(0, 0, 0, 0)

        # Solvent & conditions
        cond_group = QGroupBox("Solvent & Conditions")
        cond_layout = QFormLayout()
        self.se_solvent_combo = QComboBox()
        # Populate from viscosity dataset keys (Custom last)
        self.solvents = []
        for name in sorted(viscosity_and_solvent_mw.__globals__['nmr_solvent_data'].SOLVENT_DATA.keys()):
            if name != "Custom":
                self.solvents.append(name)
        self.solvents.append("Custom")
        self.se_solvent_combo.addItems(self.solvents)
        self.se_solvent_combo.currentTextChanged.connect(self.update_se_viscosity)

        self.se_temp_input = QLineEdit("298.15")
        self.se_temp_input.setPlaceholderText("Kelvin")
        self.se_temp_input.setValidator(QDoubleValidator(0.1, 1000.0, 2))
        self.se_temp_input.textChanged.connect(self.update_se_viscosity)

        self.se_visc_input = QLineEdit()
        self.se_visc_input.setPlaceholderText("Pa.s")
        self.se_visc_input.setReadOnly(True)

        cond_layout.addRow("Solvent:", self.se_solvent_combo)
        cond_layout.addRow("Temperature (K):", self.se_temp_input)
        cond_layout.addRow("Viscosity (η) [Pa·s]:", self.se_visc_input)
        cond_group.setLayout(cond_layout)
        layout.addWidget(cond_group)

        # Shape factor & target
        middle_layout = QHBoxLayout()

        shape_group = QGroupBox("Shape Factor (Boundary)")
        shape_layout = QVBoxLayout()
        self.se_shape_label = QLabel("6.00 π (Stick / Sphere)")
        self.se_shape_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        label_font = self.se_shape_label.font()
        label_font.setBold(True)
        self.se_shape_label.setFont(label_font)

        self.se_shape_slider = QSlider(Qt.Orientation.Horizontal)
        self.se_shape_slider.setMinimum(80)
        self.se_shape_slider.setMaximum(120)
        self.se_shape_slider.setValue(120)  # 6.00π
        self.se_shape_slider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.se_shape_slider.setTickInterval(10)
        self.se_shape_slider.valueChanged.connect(self.update_se_shape_label)
        shape_layout.addWidget(self.se_shape_label)
        shape_layout.addWidget(self.se_shape_slider)
        shape_group.setLayout(shape_layout)
        middle_layout.addWidget(shape_group, 1)

        mode_group = QGroupBox("Calculation Target")
        mode_layout = QHBoxLayout()
        self.se_mode_bg = QButtonGroup()
        self.se_radio_calc_rh = QRadioButton("Calculate rH")
        self.se_radio_calc_d = QRadioButton("Calculate D")
        self.se_radio_calc_rh.setChecked(True)
        self.se_mode_bg.addButton(self.se_radio_calc_rh)
        self.se_mode_bg.addButton(self.se_radio_calc_d)
        mode_layout.addWidget(self.se_radio_calc_rh)
        mode_layout.addWidget(self.se_radio_calc_d)
        mode_group.setLayout(mode_layout)
        middle_layout.addWidget(mode_group, 2)
        layout.addLayout(middle_layout)
        self.se_mode_bg.buttonToggled.connect(self.toggle_se_inputs)

        # Parameters
        input_group = QGroupBox("Parameters")
        input_layout = QFormLayout()

        # D container
        self.se_d_container = QWidget()
        d_layout = QHBoxLayout(self.se_d_container)
        d_layout.setContentsMargins(0, 0, 0, 0)
        self.se_d_type = QComboBox()
        self.se_d_type.addItems(["D", "log D"])
        self.se_d_val = QLineEdit()
        self.se_d_val.setPlaceholderText("e.g. -9.00")  # default until dynamic change
        self.se_d_unit = QComboBox()
        self.se_d_unit.addItems(["m²/s", "cm²/s"])
        d_layout.addWidget(self.se_d_type)
        d_layout.addWidget(self.se_d_val)
        d_layout.addWidget(self.se_d_unit)
        input_layout.addRow("Diffusion Coeff:", self.se_d_container)

        # rH container
        self.se_rh_container = QWidget()
        rh_layout = QHBoxLayout(self.se_rh_container)
        rh_layout.setContentsMargins(0, 0, 0, 0)
        self.se_rh_val = QLineEdit()
        self.se_rh_val.setPlaceholderText("e.g. 3.5")
        self.se_rh_unit = QComboBox()
        self.se_rh_unit.addItems(["Å", "nm"])
        rh_layout.addWidget(self.se_rh_val)
        rh_layout.addWidget(self.se_rh_unit)
        input_layout.addRow("Hydrodynamic Radius:", self.se_rh_container)
        input_group.setLayout(input_layout)
        layout.addWidget(input_group)

        # Dynamic placeholder for D/logD (Stokes–Einstein)
        self.se_d_type.currentTextChanged.connect(self.update_se_d_placeholder)
        self.update_se_d_placeholder(self.se_d_type.currentText())

        # Calculate button
        self.se_btn_calc = QPushButton("Calculate (Stokes–Einstein)")
        self.se_btn_calc.setFixedHeight(40)
        self.se_btn_calc.setStyleSheet("background-color: #3498db; color: white; font-weight: bold;")
        self.se_btn_calc.clicked.connect(self.calculate_se)
        layout.addWidget(self.se_btn_calc)

        # Results
        self.se_result_label = QLabel("Waiting for input...")
        self.se_result_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.se_result_label.setStyleSheet("font-size: 14px;")
        self.se_result_label.setTextInteractionFlags(Qt.TextInteractionFlag.TextSelectableByMouse)
        layout.addWidget(self.se_result_label)

        # Initialize
        self.update_se_viscosity()
        self.toggle_se_inputs()

    # ---------------- SEGWE UI & Logic ----------------
    def init_segwe_ui(self):
        layout = QVBoxLayout(self.page_segwe)
        layout.setContentsMargins(0, 0, 0, 0)

        # Solvent & conditions
        cond_group = QGroupBox("Solvent & Conditions")
        cond_layout = QFormLayout()
        self.sg_solvent_combo = QComboBox()
        self.sg_solvent_combo.addItems(self.solvents)
        self.sg_solvent_combo.currentTextChanged.connect(self.update_segwe_params)

        self.sg_temp_input = QLineEdit("298.15")
        self.sg_temp_input.setPlaceholderText("Kelvin")
        self.sg_temp_input.setValidator(QDoubleValidator(0.1, 1000.0, 2))
        self.sg_temp_input.textChanged.connect(self.update_segwe_params)

        self.sg_visc_input = QLineEdit()
        self.sg_visc_input.setPlaceholderText("Pa.s")
        self.sg_visc_input.setReadOnly(True)

        self.sg_mw_solv_input = QLineEdit()
        self.sg_mw_solv_input.setPlaceholderText("g/mol")
        self.sg_mw_solv_input.setReadOnly(True)

        cond_layout.addRow("Solvent:", self.sg_solvent_combo)
        cond_layout.addRow("Temperature (K):", self.sg_temp_input)
        cond_layout.addRow("Viscosity (η) [Pa·s]:", self.sg_visc_input)
        cond_layout.addRow("Solvent MW [g/mol]:", self.sg_mw_solv_input)
        cond_group.setLayout(cond_layout)
        layout.addWidget(cond_group)

        # Target mode
        mode_group = QGroupBox("Calculation Target")
        mode_layout = QHBoxLayout()
        self.sg_mode_bg = QButtonGroup()
        self.sg_radio_calc_mw = QRadioButton("Input D to est. MW and rH")
        self.sg_radio_calc_d = QRadioButton("Input MW to est. rH and D")
        self.sg_radio_calc_rh = QRadioButton("Input rH to est. D and MW")
        self.sg_radio_calc_mw.setChecked(True)
        self.sg_mode_bg.addButton(self.sg_radio_calc_mw)
        self.sg_mode_bg.addButton(self.sg_radio_calc_d)
        self.sg_mode_bg.addButton(self.sg_radio_calc_rh)
        mode_layout.addWidget(self.sg_radio_calc_mw)
        mode_layout.addWidget(self.sg_radio_calc_d)
        mode_layout.addWidget(self.sg_radio_calc_rh)
        mode_group.setLayout(mode_layout)
        layout.addWidget(mode_group)
        self.sg_mode_bg.buttonToggled.connect(self.toggle_segwe_inputs)

        # Parameters
        input_group = QGroupBox("Parameters")
        input_layout = QFormLayout()

        # D container
        self.sg_d_container = QWidget()
        d_layout = QHBoxLayout(self.sg_d_container)
        d_layout.setContentsMargins(0, 0, 0, 0)
        self.sg_d_type = QComboBox()
        self.sg_d_type.addItems(["D", "log D"])
        self.sg_d_val = QLineEdit()
        self.sg_d_val.setPlaceholderText("e.g. -9.00")
        self.sg_d_unit = QComboBox()
        self.sg_d_unit.addItems(["m²/s", "cm²/s"])
        d_layout.addWidget(self.sg_d_type)
        d_layout.addWidget(self.sg_d_val)
        d_layout.addWidget(self.sg_d_unit)
        input_layout.addRow("Diffusion Coeff:", self.sg_d_container)

        # MW container
        self.sg_mw_container = QWidget()
        mw_layout = QHBoxLayout(self.sg_mw_container)
        mw_layout.setContentsMargins(0, 0, 0, 0)
        self.sg_mw_val = QLineEdit()
        self.sg_mw_val.setPlaceholderText("e.g. 150.0")
        self.sg_mw_unit = QLabel("g/mol")
        mw_layout.addWidget(self.sg_mw_val)
        mw_layout.addWidget(self.sg_mw_unit)
        input_layout.addRow("Solute MW:", self.sg_mw_container)

        # rH container
        self.sg_rh_container = QWidget()
        rh_layout = QHBoxLayout(self.sg_rh_container)
        rh_layout.setContentsMargins(0, 0, 0, 0)
        self.sg_rh_val = QLineEdit()
        self.sg_rh_val.setPlaceholderText("e.g. 3.5")
        self.sg_rh_unit = QComboBox()
        self.sg_rh_unit.addItems(["Å", "nm"])
        rh_layout.addWidget(self.sg_rh_val)
        rh_layout.addWidget(self.sg_rh_unit)
        input_layout.addRow("Hydrodynamic Radius:", self.sg_rh_container)

        input_group.setLayout(input_layout)
        layout.addWidget(input_group)

        # Dynamic placeholder for D/logD (SEGWE)
        self.sg_d_type.currentTextChanged.connect(self.update_segwe_d_placeholder)
        self.update_segwe_d_placeholder(self.sg_d_type.currentText())

        # Calculate button
        self.sg_btn_calc = QPushButton("Calculate (SEGWE)")
        self.sg_btn_calc.setFixedHeight(40)
        self.sg_btn_calc.setStyleSheet("background-color: #3498db; color: white; font-weight: bold;")
        self.sg_btn_calc.clicked.connect(self.calculate_segwe)
        layout.addWidget(self.sg_btn_calc)

        # Results
        self.sg_result_label = QLabel("Waiting for input...")
        self.sg_result_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.sg_result_label.setStyleSheet("font-size: 14px;")
        self.sg_result_label.setTextInteractionFlags(Qt.TextInteractionFlag.TextSelectableByMouse)
        layout.addWidget(self.sg_result_label)

        # Initialize
        self.update_segwe_params()
        self.toggle_segwe_inputs()

    # ---------------- Shared utils ----------------
    def toggle_method_ui(self, index):
        self.stack.setCurrentIndex(index)
        self.report_field.clear()

    # Stokes–Einstein
    def toggle_se_inputs(self):
        if self.se_radio_calc_rh.isChecked():
            self.se_d_container.setEnabled(True)
            self.se_rh_container.setEnabled(False)
            self.se_rh_val.clear()
        else:
            self.se_d_container.setEnabled(False)
            self.se_rh_container.setEnabled(True)
            self.se_d_val.clear()

    def update_se_shape_label(self, value):
        factor = value / 20.0
        desc = ""
        if math.isclose(factor, 6.0, abs_tol=0.01):
            desc = "(Stick / Sphere)"
        elif math.isclose(factor, 4.0, abs_tol=0.01):
            desc = "(Slip)"
        self.se_shape_label.setText(f"{factor:.2f} π {desc}")

    def update_se_viscosity(self):
        solvent = self.se_solvent_combo.currentText()
        temp_str = self.se_temp_input.text()
        if solvent == "Custom":
            self.se_visc_input.setReadOnly(False)
            self.se_visc_input.setPlaceholderText("Enter manual value")
            return
        self.se_visc_input.setReadOnly(True)
        try:
            T = float(temp_str) if temp_str else None
        except ValueError:
            T = None
        eta, _mw = viscosity_and_solvent_mw(solvent, T) if T else (None, None)
        self.se_visc_input.setText(f"{eta:.6e}" if eta is not None else "")

    def update_se_d_placeholder(self, text: str):
        """Update placeholder & tooltip for D/logD input (Stokes–Einstein page)."""
        if text == "log D":
            self.se_d_val.setPlaceholderText("e.g. -9.00")
            self.se_d_val.setToolTip(
                "Enter log10(D).\nExample: -9.00 corresponds to D ≈ 1×10⁻⁹ m²/s.\n"
                "Use the unit dropdown to indicate m²/s or cm²/s."
            )
        else:
            self.se_d_val.setPlaceholderText("e.g. 1.0e-9")
            self.se_d_val.setToolTip(
                "Enter D (diffusion coefficient).\nScientific notation allowed, e.g. 1e-9.\n"
                "Use the unit dropdown to indicate m²/s or cm²/s."
            )

    def calculate_se(self):
        self.report_field.clear()
        try:
            temp_str = self.se_temp_input.text()
            visc_str = self.se_visc_input.text()
            if not temp_str or not visc_str:
                msg = "Missing Temperature or Viscosity"
                self.se_result_label.setText(f"Error: {msg}")
                self.show_error("Input Error", msg)
                return
            T = float(temp_str)
            eta = float(visc_str)
            C = self.se_shape_slider.value() / 20.0

            if self.se_radio_calc_rh.isChecked():
                d_val_str = self.se_d_val.text()
                if not d_val_str:
                    msg = "Enter Diffusion Coefficient"
                    self.se_result_label.setText(f"Error: {msg}")
                    self.show_error("Input Error", msg)
                    return
                raw_d = float(d_val_str)
                unit = self.se_d_unit.currentText()
                is_log = (self.se_d_type.currentText() == "log D")
                # Normalize D to m²/s
                D = (10.0 ** raw_d) if is_log else raw_d
                if unit == "cm²/s":
                    D *= 1e-4
                if D <= 0:
                    msg = "D must be positive"
                    self.se_result_label.setText(f"Error: {msg}")
                    self.show_error("Input Error", msg)
                    return
                logD_val = math.log10(D)
                rH_m = se_rh_from_D(D, T, eta, C)
                rH_angstrom = rH_m * 1e10
                rH_nm = rH_m * 1e9
                self.se_result_label.setText(
                    f"Hydrodynamic Radius (rH) [using {C:.2f}π]:\n"
                    f"{rH_angstrom:.2f} Å \n {rH_nm:.2f} nm"
                )
                self.report_field.setText(f"-logD = {-logD_val:.2f}, hydrodynamic radius = {rH_angstrom:.2f} Å")
            else:
                rh_val_str = self.se_rh_val.text()
                if not rh_val_str:
                    msg = "Enter Radius"
                    self.se_result_label.setText(f"Error: {msg}")
                    self.show_error("Input Error", msg)
                    return
                raw_rh = float(rh_val_str)
                rh_unit = self.se_rh_unit.currentText()
                rH = raw_rh * (1e-10 if rh_unit == "Å" else 1e-9)
                if rH <= 0:
                    msg = "Radius must be positive"
                    self.se_result_label.setText(f"Error: {msg}")
                    self.show_error("Input Error", msg)
                    return
                D_m2s = se_D_from_rh(rH, T, eta, C)
                D_cm2s = D_m2s * 1e4
                logD = math.log10(D_m2s)
                self.se_result_label.setText(
                    "Diffusion Coefficient (D) [using {0:.2f}π]:\n".format(C) +
                    f"{D_m2s:.2e} m²/s\n"
                    f"{D_cm2s:.2e} cm²/s\n"
                    f"log D: {logD:.2f}"
                )
                self.report_field.setText(f"-logD = {-logD:.2f}, hydrodynamic radius = {raw_rh:.2f} {rh_unit}")
        except ValueError:
            msg = "Invalid numerical input"
            self.se_result_label.setText(f"Error: {msg}")
            self.show_error("Input Error", msg)
        except ZeroDivisionError:
            msg = "Division by zero"
            self.se_result_label.setText(f"Error: {msg}")
            self.show_error("Computation Error", msg)

    # SEGWE
    def toggle_segwe_inputs(self):
        if self.sg_radio_calc_mw.isChecked():
            self.sg_d_container.setEnabled(True)
            self.sg_mw_container.setEnabled(False)
            self.sg_rh_container.setEnabled(False)
            self.sg_mw_val.clear()
            self.sg_rh_val.clear()
        elif self.sg_radio_calc_d.isChecked():
            self.sg_d_container.setEnabled(False)
            self.sg_mw_container.setEnabled(True)
            self.sg_rh_container.setEnabled(False)
            self.sg_d_val.clear()
            self.sg_rh_val.clear()
        else:
            self.sg_d_container.setEnabled(False)
            self.sg_mw_container.setEnabled(False)
            self.sg_rh_container.setEnabled(True)
            self.sg_d_val.clear()
            self.sg_mw_val.clear()

    def update_segwe_params(self):
        solvent = self.sg_solvent_combo.currentText()
        temp_str = self.sg_temp_input.text()
        if solvent == "Custom":
            self.sg_visc_input.setReadOnly(False)
            self.sg_visc_input.setPlaceholderText("Manual Value")
            self.sg_mw_solv_input.setReadOnly(False)
            self.sg_mw_solv_input.setPlaceholderText("Manual Value")
            return
        self.sg_visc_input.setReadOnly(True)
        self.sg_mw_solv_input.setReadOnly(True)
        try:
            T = float(temp_str) if temp_str else None
        except ValueError:
            T = None
        eta, mw_s = viscosity_and_solvent_mw(solvent, T) if T else (None, None)
        self.sg_visc_input.setText(f"{eta:.6e}" if eta is not None else "")
        self.sg_mw_solv_input.setText(f"{mw_s:.2f}" if mw_s is not None else "")

    def update_segwe_d_placeholder(self, text: str):
        """Update placeholder & tooltip for D/logD input (SEGWE page)."""
        if text == "log D":
            self.sg_d_val.setPlaceholderText("e.g. -9.00")
            self.sg_d_val.setToolTip(
                "Enter log10(D).\nExample: -9.00 corresponds to D ≈ 1×10⁻⁹ m²/s.\n"
                "Use the unit dropdown to indicate m²/s or cm²/s."
            )
        else:
            self.sg_d_val.setPlaceholderText("e.g. 1.0e-9")
            self.sg_d_val.setToolTip(
                "Enter D (diffusion coefficient).\nScientific notation allowed, e.g. 1e-9.\n"
                "Use the unit dropdown to indicate m²/s or cm²/s."
            )

    def calculate_segwe(self):
        self.report_field.clear()
        try:
            temp_str = self.sg_temp_input.text()
            visc_str = self.sg_visc_input.text()
            mws_str = self.sg_mw_solv_input.text()
            if not temp_str or not visc_str or not mws_str:
                msg = "Missing Conditions (T, η, or MW_S)"
                self.sg_result_label.setText(f"Error: {msg}")
                self.show_error("Input Error", msg)
                return

            T = float(temp_str)
            eta = float(visc_str)
            MW_S = float(mws_str)

            if self.sg_radio_calc_mw.isChecked():
                d_val_str = self.sg_d_val.text()
                if not d_val_str:
                    msg = "Enter Diffusion Coefficient"
                    self.sg_result_label.setText(f"Error: {msg}")
                    self.show_error("Input Error", msg)
                    return
                raw_d = float(d_val_str)
                is_log = (self.sg_d_type.currentText() == "log D")
                unit = self.sg_d_unit.currentText()
                target_D = (10.0 ** raw_d) if is_log else raw_d
                if unit == "cm²/s":
                    target_D *= 1e-4
                if target_D <= 0:
                    msg = "D must be positive"
                    self.sg_result_label.setText(f"Error: {msg}")
                    self.show_error("Input Error", msg)
                    return
                logD_val = math.log10(target_D)
                estimated_MW, r_eff_final = segwe_estimate_MW_from_D(T, eta, MW_S, target_D)
                rH_angstrom = r_eff_final * 1e10
                self.sg_result_label.setText(
                    f"Estimated MW: {estimated_MW:.2f} g/mol\n"
                    f"(Effective rH: {rH_angstrom:.2f} Å)"
                )
                self.report_field.setText(
                    f"-logD = {-logD_val:.2f}, hydrodynamic radius = {rH_angstrom:.2f} Å, "
                    f"estimated MW = {estimated_MW:.2f} g/mol"
                )

            elif self.sg_radio_calc_d.isChecked():
                mw_str = self.sg_mw_val.text()
                if not mw_str:
                    msg = "Enter Solute MW"
                    self.sg_result_label.setText(f"Error: {msg}")
                    self.show_error("Input Error", msg)
                    return
                MW = float(mw_str)
                if MW <= 0:
                    msg = "MW must be positive"
                    self.sg_result_label.setText(f"Error: {msg}")
                    self.show_error("Input Error", msg)
                    return
                D, r_eff = segwe_D(T, eta, MW_S, MW)
                D_cm2s = D * 1e4
                logD = math.log10(D)
                rH_angstrom = r_eff * 1e10
                self.sg_result_label.setText(
                    "Diffusion Coefficient (D):\n"
                    f"{D:.2e} m²/s\n"
                    f"{D_cm2s:.2e} cm²/s\n"
                    f"log D: {logD:.2f}"
                )
                self.report_field.setText(
                    f"-logD = {-logD:.2f}, hydrodynamic radius = {rH_angstrom:.2f} Å, estimated MW = {MW:.2f} g/mol"
                )

            else:
                rh_val_str = self.sg_rh_val.text()
                if not rh_val_str:
                    msg = "Enter Hydrodynamic Radius"
                    self.sg_result_label.setText(f"Error: {msg}")
                    self.show_error("Input Error", msg)
                    return
                raw_rh = float(rh_val_str)
                rh_unit = self.sg_rh_unit.currentText()
                rH_m = raw_rh * (1e-10 if rh_unit == "Å" else 1e-9)
                if rH_m <= 0:
                    msg = "Radius must be positive"
                    self.sg_result_label.setText(f"Error: {msg}")
                    self.show_error("Input Error", msg)
                    return
                # Invert SEGWE radius relation to get MW from rH:
                MW_kg = (4.0 * PI * RHO_EFF * NA * (rH_m ** 3)) / 3.0
                MW_g = MW_kg * 1000.0
                D, _ = segwe_D(T, eta, MW_S, MW_g)
                logD = math.log10(D)
                rH_angstrom = rH_m * 1e10
                self.sg_result_label.setText(
                    f"Estimated MW: {MW_g:.2f} g/mol\n"
                    "Diffusion Coefficient (D):\n"
                    f"{D:.2e} m²/s\n"
                    f"log D: {logD:.2f}"
                )
                self.report_field.setText(
                    f"-logD = {-logD:.2f}, hydrodynamic radius = {rH_angstrom:.2f} Å, estimated MW = {MW_g:.2f} g/mol"
                )

        except ValueError:
            msg = "Invalid numerical input"
            self.sg_result_label.setText(f"Error: {msg}")
            self.show_error("Input Error", msg)

    # --- Copy helpers (Edit menu compatibility) ---
    def copy_results(self):
        """Copy the visible results label (based on current page) to clipboard."""
        text = self.se_result_label.text() if self.stack.currentIndex() == 0 else self.sg_result_label.text()
        self.copy_text(text)

    def copy_report(self):
        """Copy the report string to clipboard."""
        self.copy_text(self.report_field.text())

    # Optional UX
    def clear_inputs(self):
        """Reset editable inputs to sensible defaults."""
        # Stokes–Einstein
        self.se_solvent_combo.setCurrentIndex(0)
        self.se_temp_input.setText("298.15")
        self.se_visc_input.clear()  # auto-populated
        self.se_shape_slider.setValue(120)  # 6.00π
        self.se_radio_calc_rh.setChecked(True)
        self.se_d_type.setCurrentIndex(0)
        self.se_d_val.clear()
        self.se_d_unit.setCurrentIndex(0)
        self.se_rh_val.clear()
        self.se_rh_unit.setCurrentIndex(0)
        self.se_result_label.setText("Waiting for input...")
        self.update_se_d_placeholder(self.se_d_type.currentText())

        # SEGWE
        self.sg_solvent_combo.setCurrentIndex(0)
        self.sg_temp_input.setText("298.15")
        self.sg_visc_input.clear()  # auto-populated
        self.sg_mw_solv_input.clear()  # auto-populated
        self.sg_radio_calc_mw.setChecked(True)
        self.sg_d_type.setCurrentIndex(0)
        self.sg_d_val.clear()
        self.sg_d_unit.setCurrentIndex(0)
        self.sg_mw_val.clear()
        self.sg_rh_val.clear()
        self.sg_rh_unit.setCurrentIndex(0)
        self.sg_result_label.setText("Waiting for input...")
        self.update_segwe_d_placeholder(self.sg_d_type.currentText())

        # Refresh computed fields
        self.update_se_viscosity()