# -*- coding: utf-8 -*-
"""solvent_misc

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KiTllgsQcTAqZwCOVxnq5Lx-MnlTCcCP
"""

from typing import Optional, List, Dict
from PyQt6.QtWidgets import (
    QWidget, QVBoxLayout, QLabel, QTableWidget, QTableWidgetItem,
    QHeaderView, QStyledItemDelegate, QStyleOptionViewItem, QApplication,
    QGroupBox, QHBoxLayout, QToolTip
)
from PyQt6.QtCore import Qt, QEvent, QPoint, QSize, QRect
from PyQt6.QtGui import QBrush, QColor, QPainter, QFontMetrics, QPalette

# Shared base and helpers (already in your project)
from logic.shared_functions import BaseWidget, ensure_instruction_page

# Data module (generated from miscibility.txt; see exporter)
# Expected names: SOLVENTS: List[str], MATRIX: Dict[str, Dict[str, str]]
try:
    from lib.miscibility_data import SOLVENTS, MATRIX
except Exception:
    SOLVENTS = []
    MATRIX: Dict[str, Dict[str, str]] = {}


class HoverHighlightTable(QTableWidget):
    """QTableWidget that highlights row & column under the mouse pointer."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._hover_row: Optional[int] = None
        self._hover_col: Optional[int] = None
        self.setMouseTracking(True)  # required for hover updates
        self.viewport().installEventFilter(self)

        # UX: read-only table with no selection
        self.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)
        self.setSelectionMode(QTableWidget.SelectionMode.NoSelection)
        self.setFocusPolicy(Qt.FocusPolicy.NoFocus)

        # Palette-aware brushes for row/column shading
        self._rebuild_hover_brushes() # Initial call to set brushes

    def eventFilter(self, obj, event):
        if obj is self.viewport() and event.type() == QEvent.Type.MouseMove:
            self._update_hover(event.pos())
            return False
        elif obj is self.viewport() and event.type() == QEvent.Type.Leave:
            self._clear_hover()
            return False
        return super().eventFilter(obj, event)

    def _update_hover(self, pos: QPoint):
        item = self.itemAt(pos)
        r = item.row() if item else -1
        c = item.column() if item else -1
        if r == self._hover_row and c == self._hover_col:
            return
        self._paint_row_col(self._hover_row, self._hover_col, clear=True)
        self._hover_row, self._hover_col = r, c
        self._paint_row_col(r, c, clear=False)

    def _clear_hover(self):
        self._paint_row_col(self._hover_row, self._hover_col, clear=True)
        self._hover_row, self._hover_col = None, None

    def _paint_row_col(self, r: Optional[int], c: Optional[int], clear: bool):
        rows = self.rowCount()
        cols = self.columnCount()
        if r is None or c is None or r < 0 or c < 0:
            return
        # Shade entire row r
        for j in range(cols):
            it = self.item(r, j)
            if it:
                it.setBackground(self._none_brush if clear else self._row_brush)
        # Shade entire column c (avoid double-shading intersection)
        for i in range(rows):
            it = self.item(i, c)
            if it:
                if not clear and i == r:
                    continue
                it.setBackground(self._none_brush if clear else self._col_brush)

    def _rebuild_hover_brushes(self) -> None:
        pal = self.palette()
        hl = pal.color(self.palette().ColorRole.Highlight)
        self._row_brush = QBrush(QColor(hl.red(), hl.green(), hl.blue(), 64))
        self._col_brush = QBrush(QColor(hl.red(), hl.green(), hl.blue(), 48))
        self._none_brush = QBrush(Qt.GlobalColor.transparent)

    def event(self, e):
        if e.type() == QEvent.Type.PaletteChange:
            self._rebuild_hover_brushes()
            self.viewport().update()
            return True
        return super().event(e)

class RotateHeaderDelegate(QStyledItemDelegate):
    def paint(self, painter: QPainter, option: QStyleOptionViewItem, index):
        if index.row() == 0 and index.column() >= 1:
            painter.save()
            brush = None
            if option.widget and hasattr(option.widget, "item"):
                item = option.widget.item(index.row(), index.column())
                if item is not None:
                    brush = item.background()
            if brush is None or not brush.style():
                brush = option.palette.base()
            painter.fillRect(option.rect, brush)
            painter.translate(option.rect.left(), option.rect.bottom())
            painter.rotate(-90)
            local_rect = QRect(0, 0, option.rect.height(), option.rect.width())
            text = index.data() or ""
            painter.setPen(option.palette.text().color())
            painter.drawText(local_rect, Qt.AlignmentFlag.AlignCenter, text)
            painter.restore()
        else:
            super().paint(painter, option, index)

    def sizeHint(self, option: QStyleOptionViewItem, index) -> QSize:
        if index.row() == 0 and index.column() >= 1:
            text = index.data() or ""
            fm = option.fontMetrics
            w = fm.horizontalAdvance(text) + 8
            h = fm.height() + 6
            return QSize(h, w)
        return QStyledItemDelegate.sizeHint(self, option, index)


class SolventMiscibilityWidget(BaseWidget):
    """Hover-interactive solvent miscibility grid."""
    help_key = "solvent_misc"  # -> instructions/solvent_misc_inst.html

    def __init__(self, parent: Optional[QWidget] = None):
        super().__init__(parent)
        self._solvents: List[str] = list(SOLVENTS)  # keep order from data module
        self.table: Optional[HoverHighlightTable] = None
        self._init_ui()
        # Create placeholder instructions if missing
        ensure_instruction_page("instructions", self.get_help_filename(), self.get_help_title())

    def _is_dark_palette(self) -> bool:
        pal = QApplication.palette()
        base = pal.color(pal.ColorRole.Base)
        text = pal.color(pal.ColorRole.Text)
        return base.value() < text.value()

    def _apply_table_background_for_theme(self) -> None:
        if self.table is None:
            return
        pal_app = QApplication.palette()
        if self._is_dark_palette():
            pal = pal_app
            win = pal_app.color(pal_app.ColorRole.Window)
            custom_grey = QColor(win.red(), win.green(), win.blue(), 220)
            pal.setColor(pal.ColorRole.Base, custom_grey)
            pal.setColor(pal.ColorRole.AlternateBase, custom_grey)
            self.table.setPalette(pal)
        else:
            self.table.setPalette(pal_app)
        self.table.viewport().setAutoFillBackground(True)
        self.table.viewport().update()

    def _apply_tooltip_palette(self) -> None:
        pal = QApplication.palette()
        tip_base = pal.color(QPalette.ColorRole.ToolTipBase)
        tip_text = pal.color(QPalette.ColorRole.ToolTipText)
        p = QPalette()
        p.setColor(QPalette.ColorRole.ToolTipBase, tip_base)
        p.setColor(QPalette.ColorRole.ToolTipText, tip_text)

        try:
            QToolTip.setPalette(p)
        except Exception:
            pass

    def event(self, e):
        if e.type() in (QEvent.Type.PaletteChange, QEvent.Type.ApplicationFontChange, QEvent.Type.FontChange):
            self._apply_table_background_for_theme()
            if self.table is not None and hasattr(self.table, "_rebuild_hover_brushes"):
                self.table._rebuild_hover_brushes()
                self.table.viewport().update()
            self._refresh_item_fonts()
            self._apply_tooltip_palette()
            self.update()
            return True
        return super().event(e)

    def _refresh_item_fonts(self) -> None:
        if self.table is None:
            return
        base = self.table.font()
        base.setBold(True)
        rows = self.table.rowCount()
        cols = self.table.columnCount()
        for r in range(1, rows):
            for c in range(1, cols):
                it = self.table.item(r, c)
                if not it:
                    continue
                if (it.text() or "").strip().upper() == "X":
                    it.setFont(base)

    def _init_ui(self):
        layout = QVBoxLayout(self)
        layout.setContentsMargins(10, 10, 10, 10)

        title = QLabel("Solvent Miscibility")
        f = title.font()
        f.setPointSize(16); f.setBold(True)
        title.setFont(f)
        title.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(title)

        legend_box = QGroupBox("Legend")
        legend_layout = QHBoxLayout(legend_box)
        legend_layout.setContentsMargins(10, 8, 10, 8)
        legend_layout.setSpacing(4)
        legend_layout.setAlignment(Qt.AlignmentFlag.AlignLeft)
        legend_label = QLabel(
            "<b style='color:#C80000;'>X</b> denotes immiscibility;  "
            "<span style='color:#007800;'>●</span> denotes miscibility"
        )
        legend_label.setTextFormat(Qt.TextFormat.RichText)
        legend_label.setStyleSheet("font-size: 10pt;")
        legend_label.setAlignment(Qt.AlignmentFlag.AlignLeft)
        legend_layout.addWidget(legend_label)
        legend_box.setLayout(legend_layout)
        layout.addWidget(legend_box)

        self.table = HoverHighlightTable()
        layout.addWidget(self.table)

        # Removed redundant self.table.setPalette(pal) as _apply_table_background_for_theme handles it.
        n = len(self._solvents)
        self.table.setRowCount(n + 1)
        self.table.setColumnCount(n + 1)
        self._apply_table_background_for_theme()

        # Resize/stretch policies
        hhdr = self.table.horizontalHeader()
        vhdr = self.table.verticalHeader()
        hhdr.setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        vhdr.setSectionResizeMode(QHeaderView.ResizeMode.Fixed)
        self.table.horizontalHeader().setVisible(False)
        self.table.verticalHeader().setVisible(False)
        self.table.setWordWrap(False)
        hhdr.setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
        hhdr.setMinimumSectionSize(24)
        self._rotated_delegate = RotateHeaderDelegate(self.table)
        self.table.setItemDelegate(self._rotated_delegate)

        # Top header row: row 0, columns 1..n
        for j, name in enumerate(self._solvents, start=1):
            item = QTableWidgetItem(name)
            item.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            item.setFlags(Qt.ItemFlag.ItemIsEnabled)
            self.table.setItem(0, j, item)

        # Left header column: col 0, rows 1..n
        for i, name in enumerate(self._solvents, start=1):
            item = QTableWidgetItem(name)
            item.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            item.setFlags(Qt.ItemFlag.ItemIsEnabled)
            self.table.setItem(i, 0, item)

        # Fill data cells: i>=1, j>=1
        for i, si in enumerate(self._solvents, start=1):
            row_map = MATRIX.get(si, {}) if MATRIX else {}
            for j, sj in enumerate(self._solvents, start=1):
                mark = ""

                if si == sj:
                    # Diagonal: same solvent; keep empty but give a helpful tooltip
                    cell = QTableWidgetItem("")
                    cell.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
                    cell.setFlags(Qt.ItemFlag.ItemIsEnabled)
                    cell.setToolTip(f"{si} + {sj}: Same solvent")
                else:
                    # Pull mark from the data (e.g., 'X' for immiscible, '' for miscible)
                    mark = (row_map.get(sj, "") or "").strip()

                    # Start with the raw mark; we may replace the text for miscible
                    cell = QTableWidgetItem(mark)
                    cell.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
                    cell.setFlags(Qt.ItemFlag.ItemIsEnabled)

                    if mark.upper() == "X":
                        # Immiscible: show red X (bold) and tooltip
                        cell.setForeground(QBrush(QColor(200, 0, 0)))
                        fcell = self.table.font()   # tracks app font size
                        fcell.setBold(True)
                        cell.setFont(fcell)
                        cell.setToolTip(f"{si} + {sj}: Immiscible")

                    elif mark == "" or mark.isspace():
                        # Miscible: render a green dot ● instead of blank and tooltip
                        cell.setText("●")
                        cell.setForeground(QBrush(QColor(0x00, 0x78, 0x00)))  # exact #007800
                        cell.setToolTip(f"{si} + {sj}: Miscible")

                    else:
                        # Fallback (if dataset contains other symbols/notes)
                        cell.setForeground(QBrush(QColor(0x00, 0x78, 0x00)))
                        tip_status = "Miscible" if mark == "" else mark
                        cell.setToolTip(f"{si} + {sj}: {tip_status}")

                self.table.setItem(i, j, cell)

        # Final sizing
        self.table.resizeRowsToContents()
        self.table.resizeColumnToContents(0)

        total_w = 0
        for c in range(self.table.columnCount()):
            total_w += self.table.columnWidth(c)
        total_w += self.table.frameWidth() * 2

        total_h = 0
        for r in range(self.table.rowCount()):
            total_h += self.table.rowHeight(r)
        total_h += self.table.frameWidth() * 2

        if self.table.verticalScrollBar().isVisible():
            total_w += self.table.verticalScrollBar().sizeHint().width()
        if self.table.horizontalScrollBar().isVisible():
            total_h += self.table.horizontalScrollBar().sizeHint().height()

        left, top_m, right, bottom = self.layout().getContentsMargins()
        total_w += (left + right)
        total_h += (top_m + bottom)

        top = self.window()
        if isinstance(top, QWidget):
            top.resize(total_w, total_h)
            top.setMinimumSize(total_w, total_h)

        # -- Helper --
        fm = self.table.fontMetrics()
        max_w = 0
        for name in self._solvents:
            max_w = max(max_w, fm.horizontalAdvance(name))
        desired_height = max_w + 12
        self.table.setRowHeight(0, desired_height)

        self._apply_tooltip_palette()