# -*- coding: utf-8 -*-
"""common_reagents_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZmW87z7kBpp19dRyjKa1SgDZeymirRnw
"""

# Database of common commercial reagents (Acids & Bases)
# Format: Name: {density (g/mL), mw (g/mol), purity (% w/w), formula, state, type}

COMMON_REAGENTS = {
    "Acetic Acid, Glacial": {
        "density": 1.05,
        "mw": 60.05,
        "purity": 99.5,
        "formula": "CH3COOH",
        "state": "liquid",
        "type": "acid"
    },
    "Ammonium Hydroxide (28-30% NH3)": {
        "density": 0.90,
        "mw": 17.03, # Calculations based on NH3 content usually
        "purity": 29.0, # Average
        "formula": "NH3",
        "state": "liquid",
        "type": "base"
    },
    "Formic Acid (88%)": {
        "density": 1.20,
        "mw": 46.03,
        "purity": 88.0,
        "formula": "HCOOH",
        "state": "liquid",
        "type": "acid"
    },
    "Hydrochloric Acid (37%)": {
        "density": 1.19,
        "mw": 36.46,
        "purity": 37.0,
        "formula": "HCl",
        "state": "liquid",
        "type": "acid"
    },
    "Hydrofluoric Acid (48%)": {
        "density": 1.15,
        "mw": 20.01,
        "purity": 48.0,
        "formula": "HF",
        "state": "liquid",
        "type": "acid"
    },
    "Nitric Acid (70%)": {
        "density": 1.41,
        "mw": 63.01,
        "purity": 70.0,
        "formula": "HNO3",
        "state": "liquid",
        "type": "acid"
    },
    "Perchloric Acid (70%)": {
        "density": 1.67,
        "mw": 100.46,
        "purity": 70.0,
        "formula": "HClO4",
        "state": "liquid",
        "type": "acid"
    },
    "Phosphoric Acid (85%)": {
        "density": 1.685,
        "mw": 98.00,
        "purity": 85.0,
        "formula": "H3PO4",
        "state": "liquid",
        "type": "acid"
    },
    "Potassium Hydroxide": {
        "density": "na",
        "mw": 56.11,
        "purity": 90.0,
        "formula": "KOH",
        "state": "solid",
        "type": "base"
    },
    "Sodium Hydroxide": {
        "density": "na",
        "mw": 40.00,
        "purity": 97.0,
        "formula": "NaOH",
        "state": "solid",
        "type": "base"
    },
    "Sulphuric Acid (98%)": {
        "density": 1.84,
        "mw": 98.08,
        "purity": 98.0,
        "formula": "H2SO4",
        "state": "liquid",
        "type": "acid"
    },
    "Triethylamine": {
        "density": 0.726,
        "mw": 101.19,
        "purity": 99.0,
        "formula": "N(CH2CH3)3",
        "state": "liquid",
        "type": "base"
    }
}