# -*- coding: utf-8 -*-
"""common_solvents_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TXIChcsFeA_rx5TGxtYtuL8TiREPzD8m
"""

COMMON_SOLVENTS = {
    "Water": "H2O",
    "Methanol": "CH4O",
    "Ethanol": "C2H6O",
    "Acetonitrile": "C2H3N",
    "Dichloromethane": "CH2Cl2",
    "Chloroform": "CHCl3",
    "Ethyl Acetate": "C4H8O2",
    "Acetone": "C3H6O",
    "Tetrahydrofuran": "C4H8O",
    "Hexane": "C6H14",
    "Toluene": "C7H8",
    "Dimethylsulfoxide": "C2H6OS",
    "Dimethylformamide": "C3H7NO"
}