# -*- coding: utf-8 -*-
"""
miscibility_data
Auto-generated from 'miscibility.txt' in Google Colab.
Exported: 2025-12-18T17:00:47.902607Z

Contract:
- SOLVENTS: List[str] (axis labels; order preserved)
- MATRIX: Dict[str, Dict[str, str]] ("X" = non-miscible; "" = miscible)
"""
SOLVENTS = ['Acetic acid', 'Acetone', 'Acetonitrile', 'Benzene', 'n-Butanol', 'Butyl acetate', 'Carbon tetrachloride', 'Chloroform', 'Cyclohexane', '1,2-Dichloroethane', 'Dichloromethane', 'Diethyl ether', 'Diisopropyl ether', 'Dimethyl formamide', 'Dimethyl sulfoxide', '1,4-Dioxane', 'Ethanol', 'Ethyl acetate', 'Heptane', 'Hexane', 'Methanol', 'Methyl ethyl ketone', 'n-Propanol', 'i-Propanol', 'Pentane', 'Pyridine', 'tert-Butyl methyl ether', 'Tetrahydrofuran', '2,2,4-Trimethylpentane', 'Toluene', 'Trichloroethylene', 'Water', 'Xylene']

MATRIX = {
    'Acetic acid': {'Acetic acid': '', 'Acetone': '', 'Acetonitrile': '', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': '', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': '', 'Diisopropyl ether': '', 'Dimethyl formamide': '', 'Dimethyl sulfoxide': '', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': '', 'Hexane': 'X', 'Methanol': '', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': 'X', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': '', 'Toluene': '', 'Trichloroethylene': '', 'Water': '', 'Xylene': ''},
    'Acetone': {'Acetic acid': '', 'Acetone': '', 'Acetonitrile': '', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': '', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': '', 'Diisopropyl ether': '', 'Dimethyl formamide': '', 'Dimethyl sulfoxide': '', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': '', 'Hexane': '', 'Methanol': '', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': '', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': '', 'Toluene': '', 'Trichloroethylene': '', 'Water': '', 'Xylene': ''},
    'Acetonitrile': {'Acetic acid': '', 'Acetone': '', 'Acetonitrile': '', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': 'X', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': '', 'Diisopropyl ether': '', 'Dimethyl formamide': '', 'Dimethyl sulfoxide': '', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': 'X', 'Hexane': 'X', 'Methanol': '', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': 'X', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': 'X', 'Toluene': '', 'Trichloroethylene': '', 'Water': '', 'Xylene': ''},
    'Benzene': {'Acetic acid': '', 'Acetone': '', 'Acetonitrile': '', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': '', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': '', 'Diisopropyl ether': '', 'Dimethyl formamide': '', 'Dimethyl sulfoxide': '', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': '', 'Hexane': '', 'Methanol': '', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': '', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': '', 'Toluene': '', 'Trichloroethylene': '', 'Water': 'X', 'Xylene': ''},
    'n-Butanol': {'Acetic acid': '', 'Acetone': '', 'Acetonitrile': '', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': '', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': '', 'Diisopropyl ether': '', 'Dimethyl formamide': '', 'Dimethyl sulfoxide': '', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': '', 'Hexane': '', 'Methanol': '', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': '', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': '', 'Toluene': '', 'Trichloroethylene': '', 'Water': 'X', 'Xylene': ''},
    'Butyl acetate': {'Acetic acid': '', 'Acetone': '', 'Acetonitrile': '', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': '', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': '', 'Diisopropyl ether': '', 'Dimethyl formamide': '', 'Dimethyl sulfoxide': '', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': '', 'Hexane': '', 'Methanol': '', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': '', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': '', 'Toluene': '', 'Trichloroethylene': '', 'Water': 'X', 'Xylene': ''},
    'Carbon tetrachloride': {'Acetic acid': '', 'Acetone': '', 'Acetonitrile': '', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': '', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': '', 'Diisopropyl ether': '', 'Dimethyl formamide': '', 'Dimethyl sulfoxide': '', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': '', 'Hexane': '', 'Methanol': '', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': '', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': '', 'Toluene': '', 'Trichloroethylene': '', 'Water': 'X', 'Xylene': ''},
    'Chloroform': {'Acetic acid': '', 'Acetone': '', 'Acetonitrile': '', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': '', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': '', 'Diisopropyl ether': '', 'Dimethyl formamide': '', 'Dimethyl sulfoxide': '', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': '', 'Hexane': '', 'Methanol': '', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': '', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': '', 'Toluene': '', 'Trichloroethylene': '', 'Water': 'X', 'Xylene': ''},
    'Cyclohexane': {'Acetic acid': '', 'Acetone': '', 'Acetonitrile': 'X', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': '', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': '', 'Diisopropyl ether': '', 'Dimethyl formamide': 'X', 'Dimethyl sulfoxide': 'X', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': '', 'Hexane': '', 'Methanol': 'X', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': '', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': '', 'Toluene': '', 'Trichloroethylene': '', 'Water': 'X', 'Xylene': ''},
    '1,2-Dichloroethane': {'Acetic acid': '', 'Acetone': '', 'Acetonitrile': '', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': '', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': '', 'Diisopropyl ether': '', 'Dimethyl formamide': '', 'Dimethyl sulfoxide': '', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': '', 'Hexane': '', 'Methanol': '', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': '', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': '', 'Toluene': '', 'Trichloroethylene': '', 'Water': 'X', 'Xylene': ''},
    'Dichloromethane': {'Acetic acid': '', 'Acetone': '', 'Acetonitrile': '', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': '', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': '', 'Diisopropyl ether': '', 'Dimethyl formamide': '', 'Dimethyl sulfoxide': '', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': '', 'Hexane': '', 'Methanol': '', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': '', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': '', 'Toluene': '', 'Trichloroethylene': '', 'Water': 'X', 'Xylene': ''},
    'Diethyl ether': {'Acetic acid': '', 'Acetone': '', 'Acetonitrile': '', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': '', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': '', 'Diisopropyl ether': '', 'Dimethyl formamide': '', 'Dimethyl sulfoxide': 'X', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': '', 'Hexane': '', 'Methanol': '', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': '', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': '', 'Toluene': '', 'Trichloroethylene': '', 'Water': 'X', 'Xylene': ''},
    'Diisopropyl ether': {'Acetic acid': '', 'Acetone': '', 'Acetonitrile': '', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': '', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': '', 'Diisopropyl ether': '', 'Dimethyl formamide': 'X', 'Dimethyl sulfoxide': '', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': '', 'Hexane': '', 'Methanol': '', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': '', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': '', 'Toluene': '', 'Trichloroethylene': '', 'Water': 'X', 'Xylene': ''},
    'Dimethyl formamide': {'Acetic acid': '', 'Acetone': '', 'Acetonitrile': '', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': 'X', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': '', 'Diisopropyl ether': 'X', 'Dimethyl formamide': '', 'Dimethyl sulfoxide': '', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': 'X', 'Hexane': 'X', 'Methanol': '', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': 'X', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': 'X', 'Toluene': '', 'Trichloroethylene': '', 'Water': '', 'Xylene': 'X'},
    'Dimethyl sulfoxide': {'Acetic acid': '', 'Acetone': '', 'Acetonitrile': '', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': 'X', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': 'X', 'Diisopropyl ether': '', 'Dimethyl formamide': '', 'Dimethyl sulfoxide': '', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': 'X', 'Hexane': 'X', 'Methanol': '', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': 'X', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': 'X', 'Toluene': '', 'Trichloroethylene': '', 'Water': '', 'Xylene': 'X'},
    '1,4-Dioxane': {'Acetic acid': '', 'Acetone': '', 'Acetonitrile': '', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': '', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': '', 'Diisopropyl ether': '', 'Dimethyl formamide': '', 'Dimethyl sulfoxide': '', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': '', 'Hexane': '', 'Methanol': '', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': '', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': '', 'Toluene': '', 'Trichloroethylene': '', 'Water': '', 'Xylene': ''},
    'Ethanol': {'Acetic acid': '', 'Acetone': '', 'Acetonitrile': '', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': '', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': '', 'Diisopropyl ether': '', 'Dimethyl formamide': '', 'Dimethyl sulfoxide': '', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': '', 'Hexane': '', 'Methanol': '', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': '', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': '', 'Toluene': '', 'Trichloroethylene': '', 'Water': '', 'Xylene': ''},
    'Ethyl acetate': {'Acetic acid': '', 'Acetone': '', 'Acetonitrile': '', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': '', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': '', 'Diisopropyl ether': '', 'Dimethyl formamide': '', 'Dimethyl sulfoxide': '', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': '', 'Hexane': '', 'Methanol': '', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': '', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': '', 'Toluene': '', 'Trichloroethylene': '', 'Water': 'X', 'Xylene': ''},
    'Heptane': {'Acetic acid': '', 'Acetone': '', 'Acetonitrile': 'X', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': '', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': '', 'Diisopropyl ether': '', 'Dimethyl formamide': 'X', 'Dimethyl sulfoxide': 'X', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': '', 'Hexane': '', 'Methanol': 'X', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': '', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': '', 'Toluene': '', 'Trichloroethylene': '', 'Water': 'X', 'Xylene': ''},
    'Hexane': {'Acetic acid': 'X', 'Acetone': '', 'Acetonitrile': 'X', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': '', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': '', 'Diisopropyl ether': '', 'Dimethyl formamide': 'X', 'Dimethyl sulfoxide': 'X', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': '', 'Hexane': '', 'Methanol': 'X', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': '', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': '', 'Toluene': '', 'Trichloroethylene': '', 'Water': 'X', 'Xylene': ''},
    'Methanol': {'Acetic acid': '', 'Acetone': '', 'Acetonitrile': '', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': 'X', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': '', 'Diisopropyl ether': '', 'Dimethyl formamide': '', 'Dimethyl sulfoxide': '', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': 'X', 'Hexane': 'X', 'Methanol': '', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': 'X', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': '', 'Toluene': '', 'Trichloroethylene': '', 'Water': '', 'Xylene': ''},
    'Methyl ethyl ketone': {'Acetic acid': '', 'Acetone': '', 'Acetonitrile': '', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': '', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': '', 'Diisopropyl ether': '', 'Dimethyl formamide': '', 'Dimethyl sulfoxide': '', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': '', 'Hexane': '', 'Methanol': '', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': '', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': '', 'Toluene': '', 'Trichloroethylene': '', 'Water': 'X', 'Xylene': ''},
    'n-Propanol': {'Acetic acid': '', 'Acetone': '', 'Acetonitrile': '', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': '', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': '', 'Diisopropyl ether': '', 'Dimethyl formamide': '', 'Dimethyl sulfoxide': '', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': '', 'Hexane': '', 'Methanol': '', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': '', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': '', 'Toluene': '', 'Trichloroethylene': '', 'Water': '', 'Xylene': ''},
    'i-Propanol': {'Acetic acid': '', 'Acetone': '', 'Acetonitrile': '', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': '', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': '', 'Diisopropyl ether': '', 'Dimethyl formamide': '', 'Dimethyl sulfoxide': '', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': '', 'Hexane': '', 'Methanol': '', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': '', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': '', 'Toluene': '', 'Trichloroethylene': '', 'Water': '', 'Xylene': ''},
    'Pentane': {'Acetic acid': 'X', 'Acetone': '', 'Acetonitrile': 'X', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': '', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': '', 'Diisopropyl ether': '', 'Dimethyl formamide': 'X', 'Dimethyl sulfoxide': 'X', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': '', 'Hexane': '', 'Methanol': 'X', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': '', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': '', 'Toluene': '', 'Trichloroethylene': '', 'Water': 'X', 'Xylene': ''},
    'Pyridine': {'Acetic acid': '', 'Acetone': '', 'Acetonitrile': '', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': '', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': '', 'Diisopropyl ether': '', 'Dimethyl formamide': '', 'Dimethyl sulfoxide': '', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': '', 'Hexane': '', 'Methanol': '', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': '', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': '', 'Toluene': '', 'Trichloroethylene': '', 'Water': '', 'Xylene': ''},
    'tert-Butyl methyl ether': {'Acetic acid': '', 'Acetone': '', 'Acetonitrile': '', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': '', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': '', 'Diisopropyl ether': '', 'Dimethyl formamide': '', 'Dimethyl sulfoxide': '', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': '', 'Hexane': '', 'Methanol': '', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': '', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': '', 'Toluene': '', 'Trichloroethylene': '', 'Water': 'X', 'Xylene': ''},
    'Tetrahydrofuran': {'Acetic acid': '', 'Acetone': '', 'Acetonitrile': '', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': '', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': '', 'Diisopropyl ether': '', 'Dimethyl formamide': '', 'Dimethyl sulfoxide': '', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': '', 'Hexane': '', 'Methanol': '', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': '', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': '', 'Toluene': '', 'Trichloroethylene': '', 'Water': 'X', 'Xylene': ''},
    '2,2,4-Trimethylpentane': {'Acetic acid': '', 'Acetone': '', 'Acetonitrile': 'X', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': '', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': '', 'Diisopropyl ether': '', 'Dimethyl formamide': 'X', 'Dimethyl sulfoxide': 'X', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': '', 'Hexane': '', 'Methanol': '', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': '', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': '', 'Toluene': '', 'Trichloroethylene': '', 'Water': '', 'Xylene': ''},
    'Toluene': {'Acetic acid': '', 'Acetone': '', 'Acetonitrile': '', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': '', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': '', 'Diisopropyl ether': '', 'Dimethyl formamide': '', 'Dimethyl sulfoxide': '', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': '', 'Hexane': '', 'Methanol': '', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': '', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': '', 'Toluene': '', 'Trichloroethylene': '', 'Water': 'X', 'Xylene': ''},
    'Trichloroethylene': {'Acetic acid': '', 'Acetone': '', 'Acetonitrile': '', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': '', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': '', 'Diisopropyl ether': '', 'Dimethyl formamide': '', 'Dimethyl sulfoxide': '', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': '', 'Hexane': '', 'Methanol': '', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': '', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': '', 'Toluene': '', 'Trichloroethylene': '', 'Water': 'X', 'Xylene': 'X'},
    'Water': {'Acetic acid': '', 'Acetone': '', 'Acetonitrile': '', 'Benzene': 'X', 'n-Butanol': 'X', 'Butyl acetate': 'X', 'Carbon tetrachloride': 'X', 'Chloroform': 'X', 'Cyclohexane': 'X', '1,2-Dichloroethane': 'X', 'Dichloromethane': 'X', 'Diethyl ether': 'X', 'Diisopropyl ether': 'X', 'Dimethyl formamide': '', 'Dimethyl sulfoxide': '', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': 'X', 'Heptane': 'X', 'Hexane': 'X', 'Methanol': '', 'Methyl ethyl ketone': 'X', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': 'X', 'Pyridine': '', 'tert-Butyl methyl ether': 'X', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': 'X', 'Toluene': 'X', 'Trichloroethylene': 'X', 'Water': '', 'Xylene': 'X'},
    'Xylene': {'Acetic acid': '', 'Acetone': '', 'Acetonitrile': '', 'Benzene': '', 'n-Butanol': '', 'Butyl acetate': '', 'Carbon tetrachloride': '', 'Chloroform': '', 'Cyclohexane': '', '1,2-Dichloroethane': '', 'Dichloromethane': '', 'Diethyl ether': '', 'Diisopropyl ether': '', 'Dimethyl formamide': 'X', 'Dimethyl sulfoxide': 'X', '1,4-Dioxane': '', 'Ethanol': '', 'Ethyl acetate': '', 'Heptane': '', 'Hexane': '', 'Methanol': '', 'Methyl ethyl ketone': '', 'n-Propanol': '', 'i-Propanol': '', 'Pentane': '', 'Pyridine': '', 'tert-Butyl methyl ether': '', 'Tetrahydrofuran': '', '2,2,4-Trimethylpentane': '', 'Toluene': '', 'Trichloroethylene': 'X', 'Water': 'X', 'Xylene': ''},
}
