# -*- coding: utf-8 -*-
"""ms_adducts_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AKc_V4NAOXI-UKDG3GUYKQhSTcUoJyWy
"""

"""
MS Adducts Data Module
Defines common positive and negative adducts with their chemical modifications.
"""

# Electron mass in u (atomic mass units)
ELECTRON_MASS = 0.0005485799

# Adduct Definitions
# 'add': Dictionary of elements to ADD to the neutral formula
# 'sub': Dictionary of elements to SUBTRACT from the neutral formula
# 'charge': +1 or -1
# 'mass_offset': Additional mass correction (usually -electron for pos, +electron for neg)

ADDUCTS = {
    "positive": {
        "[M]+": {
            "name": "[M]+",
            "add": {},
            "sub": {},
            "charge": 1,
            "mass_offset": -ELECTRON_MASS
        },
        "[M+H]+": {
            "name": "[M+H]+",
            "add": {"H": 1},
            "sub": {},
            "charge": 1,
            "mass_offset": -ELECTRON_MASS
        },
        "[M+NH4]+": {
            "name": "[M+NH4]+",
            "add": {"N": 1, "H": 4},
            "sub": {},
            "charge": 1,
            "mass_offset": -ELECTRON_MASS
        },
        "[M+Na]+": {
            "name": "[M+Na]+",
            "add": {"Na": 1},
            "sub": {},
            "charge": 1,
            "mass_offset": -ELECTRON_MASS
        },
        "[M+CH3OH+H]+": {
            "name": "[M+CH3OH+H]+",
            "add": {"C": 1, "H": 5, "O": 1},
            "sub": {},
            "charge": 1,
            "mass_offset": -ELECTRON_MASS
        },
        "[M+K]+": {
            "name": "[M+K]+",
            "add": {"K": 1},
            "sub": {},
            "charge": 1,
            "mass_offset": -ELECTRON_MASS
        },
        "[M+CH3CN+H]+": {
            "name": "[M+CH3CN+H]+",
            "add": {"C": 2, "H": 4, "N": 1},
            "sub": {},
            "charge": 1,
            "mass_offset": -ELECTRON_MASS
        },
        "[M+DMSO+H]+": {
            "name": "[M+DMSO+H]+",
            "add": {"C": 2, "H": 7, "O": 1, "S": 1},
            "sub": {},
            "charge": 1,
            "mass_offset": -ELECTRON_MASS
        }
    },
    "negative": {
        "[M]-": {
            "name": "[M]-",
            "add": {},
            "sub": {},
            "charge": -1,
            "mass_offset": +ELECTRON_MASS
        },
        "[M-H]-": {
            "name": "[M-H]-",
            "add": {},
            "sub": {"H": 1},
            "charge": -1,
            "mass_offset": +ELECTRON_MASS
        },
        "[M+Cl]-": {
            "name": "[M+Cl]-",
            "add": {"Cl": 1},
            "sub": {},
            "charge": -1,
            "mass_offset": +ELECTRON_MASS
        },
        "[M+HCO2]-": {
            "name": "[M+HCO2]- (Formate)",
            "add": {"H": 1, "C": 1, "O": 2},
            "sub": {},
            "charge": -1,
            "mass_offset": +ELECTRON_MASS
        },
        "[M+CH3CO2]-": {
            "name": "[M+CH3CO2]- (Acetate)",
            "add": {"C": 2, "H": 3, "O": 2},
            "sub": {},
            "charge": -1,
            "mass_offset": +ELECTRON_MASS
        },
        "[M+Br]-": {
            "name": "[M+Br]-",
            "add": {"Br": 1},
            "sub": {},
            "charge": -1,
            "mass_offset": +ELECTRON_MASS
        },
        "[M+CF3CO2]-": {
            "name": "[M+CF3CO2]- (TFA)",
            "add": {"C": 2, "F": 3, "O": 2},
            "sub": {},
            "charge": -1,
            "mass_offset": +ELECTRON_MASS
        }
    }
}