# -*- coding: utf-8 -*-
"""ms_isotopes_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gj5bnkfUA8vuAjF56Qn3a7bgYnjxJlpz
"""

"""
Isotopes Data Module
Derived from IUPAC/NIST Isotopic Compositions.
Format: {Element: {MassNumber: {'mass': float, 'abundance': float}}}
Only isotopes with non-zero natural abundance are included.
"""

ISOTOPE_DATA = {
    'H': {
        1: {'mass': 1.00782503223, 'abundance': 0.999885},
        2: {'mass': 2.01410177812, 'abundance': 0.000115}
    },
    'He': {
        3: {'mass': 3.0160293201, 'abundance': 0.00000134},
        4: {'mass': 4.00260325413, 'abundance': 0.99999866}
    },
    'Li': {
        6: {'mass': 6.0151228874, 'abundance': 0.0759},
        7: {'mass': 7.0160034366, 'abundance': 0.9241}
    },
    'Be': {
        9: {'mass': 9.012183065, 'abundance': 1.0}
    },
    'B': {
        10: {'mass': 10.01293695, 'abundance': 0.199},
        11: {'mass': 11.00930536, 'abundance': 0.801}
    },
    'C': {
        12: {'mass': 12.0000000, 'abundance': 0.9893},
        13: {'mass': 13.00335483507, 'abundance': 0.0107}
    },
    'N': {
        14: {'mass': 14.00307400443, 'abundance': 0.99632},
        15: {'mass': 15.00010889888, 'abundance': 0.00368}
    },
    'O': {
        16: {'mass': 15.99491461957, 'abundance': 0.99757},
        17: {'mass': 16.9991317565, 'abundance': 0.00038},
        18: {'mass': 17.99915961286, 'abundance': 0.00205}
    },
    'F': {
        19: {'mass': 18.99840316273, 'abundance': 1.0}
    },
    'Ne': {
        20: {'mass': 19.9924401762, 'abundance': 0.9048},
        21: {'mass': 20.993846685, 'abundance': 0.0027},
        22: {'mass': 21.991385114, 'abundance': 0.0925}
    },
    'Na': {
        23: {'mass': 22.989769282, 'abundance': 1.0}
    },
    'Mg': {
        24: {'mass': 23.985041697, 'abundance': 0.7899},
        25: {'mass': 24.985836976, 'abundance': 0.1000},
        26: {'mass': 25.982592968, 'abundance': 0.1101}
    },
    'Al': {
        27: {'mass': 26.98153853, 'abundance': 1.0}
    },
    'Si': {
        28: {'mass': 27.97692653465, 'abundance': 0.92223},
        29: {'mass': 28.9764946649, 'abundance': 0.04685},
        30: {'mass': 29.973770136, 'abundance': 0.03092}
    },
    'P': {
        31: {'mass': 30.97376199842, 'abundance': 1.0}
    },
    'S': {
        32: {'mass': 31.972070999, 'abundance': 0.9493},
        33: {'mass': 32.97145876, 'abundance': 0.0076},
        34: {'mass': 33.96786690, 'abundance': 0.0429},
        36: {'mass': 35.96708076, 'abundance': 0.0002}
    },
    'Cl': {
        35: {'mass': 34.968852682, 'abundance': 0.7576},
        37: {'mass': 36.965902602, 'abundance': 0.2424}
    },
    'Ar': {
        36: {'mass': 35.967545105, 'abundance': 0.003336},
        38: {'mass': 37.96273211, 'abundance': 0.000629},
        40: {'mass': 39.9623831237, 'abundance': 0.996035}
    },
    'K': {
        39: {'mass': 38.9637064864, 'abundance': 0.932581},
        40: {'mass': 39.963998166, 'abundance': 0.000117},
        41: {'mass': 40.9618252579, 'abundance': 0.067302}
    },
    'Ca': {
        40: {'mass': 39.962590863, 'abundance': 0.96941},
        42: {'mass': 41.95861783, 'abundance': 0.00647},
        43: {'mass': 42.95876644, 'abundance': 0.00135},
        44: {'mass': 43.95548136, 'abundance': 0.02086},
        46: {'mass': 45.9536890, 'abundance': 0.00004},
        48: {'mass': 47.95252276, 'abundance': 0.00187}
    },
    'Sc': {
        45: {'mass': 44.95590828, 'abundance': 1.0}
    },
    'Ti': {
        46: {'mass': 45.95262772, 'abundance': 0.0825},
        47: {'mass': 46.95175879, 'abundance': 0.0744},
        48: {'mass': 47.94794198, 'abundance': 0.7372},
        49: {'mass': 48.94786568, 'abundance': 0.0541},
        50: {'mass': 49.94478689, 'abundance': 0.0518}
    },
    'V': {
        50: {'mass': 49.94715601, 'abundance': 0.0025},
        51: {'mass': 50.94395704, 'abundance': 0.9975}
    },
    'Cr': {
        50: {'mass': 49.94604183, 'abundance': 0.04345},
        52: {'mass': 51.94050623, 'abundance': 0.83789},
        53: {'mass': 52.94064815, 'abundance': 0.09501},
        54: {'mass': 53.93887916, 'abundance': 0.02365}
    },
    'Mn': {
        55: {'mass': 54.93804391, 'abundance': 1.0}
    },
    'Fe': {
        54: {'mass': 53.93960899, 'abundance': 0.05845},
        56: {'mass': 55.93493633, 'abundance': 0.91754},
        57: {'mass': 56.93539284, 'abundance': 0.02119},
        58: {'mass': 57.93327443, 'abundance': 0.00282}
    },
    'Co': {
        59: {'mass': 58.93319429, 'abundance': 1.0}
    },
    'Ni': {
        58: {'mass': 57.93534241, 'abundance': 0.68077},
        60: {'mass': 59.93078559, 'abundance': 0.26223},
        61: {'mass': 60.93105557, 'abundance': 0.01140},
        62: {'mass': 61.92834537, 'abundance': 0.03634},
        64: {'mass': 63.92796682, 'abundance': 0.00926}
    },
    'Cu': {
        63: {'mass': 62.92959772, 'abundance': 0.6915},
        65: {'mass': 64.92778970, 'abundance': 0.3085}
    },
    'Zn': {
        64: {'mass': 63.92914201, 'abundance': 0.4917},
        66: {'mass': 65.92603381, 'abundance': 0.2773},
        67: {'mass': 66.92712775, 'abundance': 0.0404},
        68: {'mass': 67.92484455, 'abundance': 0.1845},
        70: {'mass': 69.9253192, 'abundance': 0.0061}
    },
    'Ga': {
        69: {'mass': 68.9255735, 'abundance': 0.60108},
        71: {'mass': 70.9247005, 'abundance': 0.39892}
    },
    'Ge': {
        70: {'mass': 69.92424875, 'abundance': 0.2057},
        72: {'mass': 71.922075826, 'abundance': 0.2745},
        73: {'mass': 72.923458956, 'abundance': 0.0775},
        74: {'mass': 73.921177761, 'abundance': 0.3650},
        76: {'mass': 75.921402726, 'abundance': 0.0773}
    },
    'As': {
        75: {'mass': 74.92159457, 'abundance': 1.0}
    },
    'Se': {
        74: {'mass': 73.922475934, 'abundance': 0.0089},
        76: {'mass': 75.919213704, 'abundance': 0.0937},
        77: {'mass': 76.919914154, 'abundance': 0.0763},
        78: {'mass': 77.91730928, 'abundance': 0.2377},
        80: {'mass': 79.9165218, 'abundance': 0.4961},
        82: {'mass': 81.9166995, 'abundance': 0.0873}
    },
    'Br': {
        79: {'mass': 78.9183376, 'abundance': 0.5069},
        81: {'mass': 80.9162897, 'abundance': 0.4931}
    },
    'Kr': {
        78: {'mass': 77.92036494, 'abundance': 0.00355},
        80: {'mass': 79.91637808, 'abundance': 0.02286},
        82: {'mass': 81.91348273, 'abundance': 0.11593},
        83: {'mass': 82.91412716, 'abundance': 0.11500},
        84: {'mass': 83.9114977282, 'abundance': 0.56987},
        86: {'mass': 85.9106106269, 'abundance': 0.17279}
    },
    'Rb': {
        85: {'mass': 84.9117897379, 'abundance': 0.7217},
        87: {'mass': 86.9091805310, 'abundance': 0.2783}
    },
    'Sr': {
        84: {'mass': 83.9134191, 'abundance': 0.0056},
        86: {'mass': 85.9092606, 'abundance': 0.0986},
        87: {'mass': 86.9088775, 'abundance': 0.0700},
        88: {'mass': 87.9056125, 'abundance': 0.8258}
    },
    'Y': {
        89: {'mass': 88.9058403, 'abundance': 1.0}
    },
    'Zr': {
        90: {'mass': 89.9047026, 'abundance': 0.5145},
        91: {'mass': 90.9056439, 'abundance': 0.1122},
        92: {'mass': 91.9050386, 'abundance': 0.1715},
        94: {'mass': 93.9063148, 'abundance': 0.1738},
        96: {'mass': 95.908275, 'abundance': 0.0280}
    },
    'Nb': {
        93: {'mass': 92.9063730, 'abundance': 1.0}
    },
    'Mo': {
        92: {'mass': 91.90680796, 'abundance': 0.14649},
        94: {'mass': 93.9050853, 'abundance': 0.09187},
        95: {'mass': 94.9058411, 'abundance': 0.15873},
        96: {'mass': 95.9046785, 'abundance': 0.16673},
        97: {'mass': 96.9060205, 'abundance': 0.09582},
        98: {'mass': 97.9054073, 'abundance': 0.24292},
        100: {'mass': 99.9074771, 'abundance': 0.09744}
    },
    'Ru': {
        96: {'mass': 95.90759025, 'abundance': 0.0554},
        98: {'mass': 97.9052868, 'abundance': 0.0187},
        99: {'mass': 98.9059341, 'abundance': 0.1276},
        100: {'mass': 99.9042143, 'abundance': 0.1260},
        101: {'mass': 100.9055769, 'abundance': 0.1706},
        102: {'mass': 101.9043441, 'abundance': 0.3155},
        104: {'mass': 103.9054275, 'abundance': 0.1862}
    },
    'Rh': {
        103: {'mass': 102.9055031, 'abundance': 1.0}
    },
    'Pd': {
        102: {'mass': 101.9056022, 'abundance': 0.0102},
        104: {'mass': 103.9040305, 'abundance': 0.1114},
        105: {'mass': 104.9050796, 'abundance': 0.2233},
        106: {'mass': 105.9034804, 'abundance': 0.2733},
        108: {'mass': 107.9038916, 'abundance': 0.2646},
        110: {'mass': 109.90517220, 'abundance': 0.1172}
    },
    'Ag': {
        107: {'mass': 106.9050916, 'abundance': 0.51839},
        109: {'mass': 108.9047553, 'abundance': 0.48161}
    },
    'Cd': {
        106: {'mass': 105.9064585, 'abundance': 0.0125},
        108: {'mass': 107.9041834, 'abundance': 0.0089},
        110: {'mass': 109.90300661, 'abundance': 0.1249},
        111: {'mass': 110.90418287, 'abundance': 0.1280},
        112: {'mass': 111.90276287, 'abundance': 0.2413},
        113: {'mass': 112.9044067, 'abundance': 0.1222},
        114: {'mass': 113.9033636, 'abundance': 0.2873},
        116: {'mass': 115.904761, 'abundance': 0.0749}
    },
    'In': {
        113: {'mass': 112.9040611, 'abundance': 0.0429},
        115: {'mass': 114.903878776, 'abundance': 0.9571}
    },
    'Sn': {
        112: {'mass': 111.9048239, 'abundance': 0.0097},
        114: {'mass': 113.9027827, 'abundance': 0.0066},
        115: {'mass': 114.903344699, 'abundance': 0.0034},
        116: {'mass': 115.90174280, 'abundance': 0.1454},
        117: {'mass': 116.90295398, 'abundance': 0.0768},
        118: {'mass': 117.9016067, 'abundance': 0.2422},
        119: {'mass': 118.90331117, 'abundance': 0.0859},
        120: {'mass': 119.90220163, 'abundance': 0.3258},
        122: {'mass': 121.9034438, 'abundance': 0.0463},
        124: {'mass': 123.9052766, 'abundance': 0.0579}
    },
    'Sb': {
        121: {'mass': 120.9038152, 'abundance': 0.5721},
        123: {'mass': 122.9042132, 'abundance': 0.4279}
    },
    'Te': {
        120: {'mass': 119.9040593, 'abundance': 0.0009},
        122: {'mass': 121.9030435, 'abundance': 0.0255},
        123: {'mass': 122.9042698, 'abundance': 0.0088},
        124: {'mass': 123.9028171, 'abundance': 0.0474},
        125: {'mass': 124.904430, 'abundance': 0.0707},
        126: {'mass': 125.9033109, 'abundance': 0.1884},
        128: {'mass': 127.90446128, 'abundance': 0.3174},
        130: {'mass': 129.906222748, 'abundance': 0.3408}
    },
    'I': {
        127: {'mass': 126.9044719, 'abundance': 1.0}
    },
    'Xe': {
        124: {'mass': 123.9058920, 'abundance': 0.00095},
        126: {'mass': 125.9042983, 'abundance': 0.00089},
        128: {'mass': 127.9035310, 'abundance': 0.01910},
        129: {'mass': 128.9047794, 'abundance': 0.26401},
        130: {'mass': 129.9035080, 'abundance': 0.04071},
        131: {'mass': 130.9050824, 'abundance': 0.21232},
        132: {'mass': 131.904155086, 'abundance': 0.26909},
        134: {'mass': 133.90539466, 'abundance': 0.10436},
        136: {'mass': 135.907214484, 'abundance': 0.08857}
    },
    'Cs': {
        133: {'mass': 132.9054519610, 'abundance': 1.0}
    },
    'Ba': {
        130: {'mass': 129.9063207, 'abundance': 0.00106},
        132: {'mass': 131.9050611, 'abundance': 0.00101},
        134: {'mass': 133.90450818, 'abundance': 0.02417},
        135: {'mass': 134.90568838, 'abundance': 0.06592},
        136: {'mass': 135.90457573, 'abundance': 0.07854},
        137: {'mass': 136.90582714, 'abundance': 0.11232},
        138: {'mass': 137.90524700, 'abundance': 0.71698}
    },
    'La': {
        138: {'mass': 137.9071116, 'abundance': 0.0009},
        139: {'mass': 138.9063533, 'abundance': 0.9991}
    },
    'Ce': {
        136: {'mass': 135.90712921, 'abundance': 0.00185},
        138: {'mass': 137.905991, 'abundance': 0.00251},
        140: {'mass': 139.9054387, 'abundance': 0.88450},
        142: {'mass': 141.9092443, 'abundance': 0.11114}
    },
    'Pr': {
        141: {'mass': 140.9076528, 'abundance': 1.0}
    },
    'Nd': {
        142: {'mass': 141.9077233, 'abundance': 0.272},
        143: {'mass': 142.9098143, 'abundance': 0.122},
        144: {'mass': 143.9100873, 'abundance': 0.238},
        145: {'mass': 144.9125736, 'abundance': 0.083},
        146: {'mass': 145.9131169, 'abundance': 0.172},
        148: {'mass': 147.916893, 'abundance': 0.057},
        150: {'mass': 149.920891, 'abundance': 0.056}
    },
    'Sm': {
        144: {'mass': 143.911999, 'abundance': 0.0307},
        147: {'mass': 146.9148979, 'abundance': 0.1499},
        148: {'mass': 147.9148227, 'abundance': 0.1124},
        149: {'mass': 148.9171847, 'abundance': 0.1382},
        150: {'mass': 149.9172755, 'abundance': 0.0738},
        152: {'mass': 151.9197324, 'abundance': 0.2675},
        154: {'mass': 153.9222093, 'abundance': 0.2275}
    },
    'Eu': {
        151: {'mass': 150.9198502, 'abundance': 0.4781},
        153: {'mass': 152.9212303, 'abundance': 0.5219}
    },
    'Gd': {
        152: {'mass': 151.9197910, 'abundance': 0.0020},
        154: {'mass': 153.9208656, 'abundance': 0.0218},
        155: {'mass': 154.9226220, 'abundance': 0.1480},
        156: {'mass': 155.9221227, 'abundance': 0.2047},
        157: {'mass': 156.9239601, 'abundance': 0.1565},
        158: {'mass': 157.9241039, 'abundance': 0.2484},
        160: {'mass': 159.9270541, 'abundance': 0.2186}
    },
    'Tb': {
        159: {'mass': 158.9253468, 'abundance': 1.0}
    },
    'Dy': {
        156: {'mass': 155.924283, 'abundance': 0.00056},
        158: {'mass': 157.924409, 'abundance': 0.00095},
        160: {'mass': 159.9251975, 'abundance': 0.02329},
        161: {'mass': 160.9269334, 'abundance': 0.18889},
        162: {'mass': 161.9267984, 'abundance': 0.25475},
        163: {'mass': 162.9287312, 'abundance': 0.24896},
        164: {'mass': 163.9291748, 'abundance': 0.28260}
    },
    'Ho': {
        165: {'mass': 164.9303221, 'abundance': 1.0}
    },
    'Er': {
        162: {'mass': 161.928778, 'abundance': 0.00139},
        164: {'mass': 163.929200, 'abundance': 0.01601},
        166: {'mass': 165.9302931, 'abundance': 0.33503},
        167: {'mass': 166.9320482, 'abundance': 0.22869},
        168: {'mass': 167.9323702, 'abundance': 0.26978},
        170: {'mass': 169.9354643, 'abundance': 0.14910}
    },
    'Tm': {
        169: {'mass': 168.9342133, 'abundance': 1.0}
    },
    'Yb': {
        168: {'mass': 167.933897, 'abundance': 0.0013},
        170: {'mass': 169.9347618, 'abundance': 0.0304},
        171: {'mass': 170.9363258, 'abundance': 0.1428},
        172: {'mass': 171.9363815, 'abundance': 0.2183},
        173: {'mass': 172.9382108, 'abundance': 0.1613},
        174: {'mass': 173.9388621, 'abundance': 0.3183},
        176: {'mass': 175.9425717, 'abundance': 0.1276}
    },
    'Lu': {
        175: {'mass': 174.9407718, 'abundance': 0.9741},
        176: {'mass': 175.9426863, 'abundance': 0.0259}
    },
    'Hf': {
        174: {'mass': 173.940040, 'abundance': 0.0016},
        176: {'mass': 175.9414086, 'abundance': 0.0526},
        177: {'mass': 176.9432207, 'abundance': 0.1860},
        178: {'mass': 177.9436988, 'abundance': 0.2728},
        179: {'mass': 178.9458161, 'abundance': 0.1362},
        180: {'mass': 179.9465500, 'abundance': 0.3508}
    },
    'Ta': {
        180: {'mass': 179.9474648, 'abundance': 0.00012},
        181: {'mass': 180.9479958, 'abundance': 0.99988}
    },
    'W': {
        180: {'mass': 179.946704, 'abundance': 0.0012},
        182: {'mass': 181.9482042, 'abundance': 0.2650},
        183: {'mass': 182.9502230, 'abundance': 0.1431},
        184: {'mass': 183.9509312, 'abundance': 0.3064},
        186: {'mass': 185.9543641, 'abundance': 0.2843}
    },
    'Re': {
        185: {'mass': 184.9529550, 'abundance': 0.3740},
        187: {'mass': 186.9557531, 'abundance': 0.6260}
    },
    'Os': {
        184: {'mass': 183.9524891, 'abundance': 0.0002},
        186: {'mass': 185.9538382, 'abundance': 0.0159},
        187: {'mass': 186.9557505, 'abundance': 0.0196},
        188: {'mass': 187.9558382, 'abundance': 0.1324},
        189: {'mass': 188.9581475, 'abundance': 0.1615},
        190: {'mass': 189.9584470, 'abundance': 0.2626},
        192: {'mass': 191.9614807, 'abundance': 0.4078}
    },
    'Ir': {
        191: {'mass': 190.9605940, 'abundance': 0.373},
        193: {'mass': 192.9629264, 'abundance': 0.627}
    },
    'Pt': {
        190: {'mass': 189.959932, 'abundance': 0.00012},
        192: {'mass': 191.9610380, 'abundance': 0.00782},
        194: {'mass': 193.9626803, 'abundance': 0.32967},
        195: {'mass': 194.9647911, 'abundance': 0.33832},
        196: {'mass': 195.9649515, 'abundance': 0.25242},
        198: {'mass': 197.967893, 'abundance': 0.07163}
    },
    'Au': {
        197: {'mass': 196.9665687, 'abundance': 1.0}
    },
    'Hg': {
        196: {'mass': 195.965833, 'abundance': 0.0015},
        198: {'mass': 197.9667690, 'abundance': 0.0997},
        199: {'mass': 198.9682799, 'abundance': 0.1687},
        200: {'mass': 199.9683260, 'abundance': 0.2310},
        201: {'mass': 200.9703023, 'abundance': 0.1318},
        202: {'mass': 201.9706430, 'abundance': 0.2986},
        204: {'mass': 203.9734939, 'abundance': 0.0687}
    },
    'Tl': {
        203: {'mass': 202.9723442, 'abundance': 0.2952},
        205: {'mass': 204.9744275, 'abundance': 0.7048}
    },
    'Pb': {
        204: {'mass': 203.9730436, 'abundance': 0.014},
        206: {'mass': 205.9744653, 'abundance': 0.241},
        207: {'mass': 206.9758969, 'abundance': 0.221},
        208: {'mass': 207.9766521, 'abundance': 0.524}
    },
    'Bi': {
        209: {'mass': 208.9803987, 'abundance': 1.0}
    },
    'Th': {
        232: {'mass': 232.0380553, 'abundance': 1.0}
    },
    'Pa': {
        231: {'mass': 231.0358840, 'abundance': 1.0}
    },
    'U': {
        234: {'mass': 234.0409521, 'abundance': 0.000054},
        235: {'mass': 235.0439299, 'abundance': 0.007204},
        238: {'mass': 238.0507882, 'abundance': 0.992742}
    }
}