# -*- coding: utf-8 -*-
"""nmr_solvent_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RisYaB09vFgvgZLB9N3xZDPUdIxds7hB
"""

"""
NMR Solvent Data Module
Contains viscosity parameters for deuterated and non-deuterated solvents.
Used for DOSY calculations.
"""

# Parameters for viscosity equation: eta = a * exp(b / T)
# eta in Pa.s (assuming 'a' is in Pa.s)
# T in Kelvin

SOLVENT_DATA = {
    "Acetonitrile-d3":          {"a": 1.78e-5, "b": 899,  "mw": 44.07,  "type": "direct"},
    "Benzene-d6":               {"a": 9.06e-6, "b": 1256, "mw": 84.15,  "type": "direct"},
    "Chloroform-d":             {"a": 2.86e-5, "b": 878,  "mw": 120.38, "type": "direct"},
    "Cyclohexane-d12":          {"a": 6.17e-6, "b": 1504, "mw": 96.23,  "type": "direct"},
    "Dimethyl Sulfoxide-d6":    {"a": 1.93e-5, "b": 1742, "mw": 84.17,  "type": "direct"},
    "Methanol-d4":              {"a": 8.62e-6, "b": 1268, "mw": 36.07,  "type": "direct"},
    "Tetrahydrofuran-d8":       {"a": 2.07e-5, "b": 930,  "mw": 80.16,  "type": "direct"},
    "Toluene-d8":               {"a": 1.50e-5, "b": 1217, "mw": 100.19, "type": "direct"},
    "Water-d2":                 {"a": 4.52e-7, "b": 2330, "mw": 20.03,  "type": "direct"},

    # Inferred Data (Estimated from non-deuterated: etaD = etaH * (MW_D / MW_H))
    "DMF-d7":                   {"ref": "DMF",           "mw_d": 80.14,  "type": "inferred"},
    "Ethanol-d6":               {"ref": "Ethanol",       "mw_d": 52.11,  "type": "inferred"},
    "Fluorobenzene-d5":         {"ref": "Fluorobenzene", "mw_d": 101.13, "type": "inferred"},

    "Custom":                   {"type": "custom"}
}

NON_DEUTERATED_REFS = {
    "DMF":           {"a": 1.93e-5, "b": 1114, "mw": 73.09},
    "Ethanol":       {"a": 4.75e-6, "b": 1790, "mw": 46.07},
    "Fluorobenzene": {"a": 1.73e-5, "b": 1051, "mw": 96.10}
}