# -*- coding: utf-8 -*-
"""nmr_common

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wlnZPDBWFtKx_Xq3URI4TVnz0a6zfODJ
"""

# -*- coding: utf-8 -*-

# Map note codes -> human-readable explanations
NOTES = {
    # ---- Examples (fill in the rest to match your dataset) ----
    # Letters should be consistent with the note codes present in DATA_1H/DATA_13C
    "a": "Asignal for HDO is also observed in (CD3)2SO (3.30 ppm) and (CD3)2CO (2.81 ppm), often seen as a 1:1:1 triplet (2JH, D = 1 Hz).",
    "b": "BHT = 2,6-Dimethyl-4-tert-butylphenol; CPME = Cyclopentyl methyl ether; DMPU = N,N′-Dimethylpropyleneurea; HMDSO = Hexamethyldisiloxane; HMPA = Hexamethylphosphoramide.",
    "c": "The signals from exchangeable protons were not always identified.",
    "d": "In some solvents, a coupling interaction between the CH2 and the OH protons may be observed (J = 5 Hz)",
    "e": "In CD3CN,the OH proton was seen as a multiplet at δ 2.69, and extra coupling was also apparent on the methylene peak.",
    "f": "Apiezon brand H grease.",
    "g": "Long-chain, linear aliphatic hydrocarbons. Their solubility in DMSO was too low to give visible peaks.",
    "h": "In some solvents, a coupling interaction between the CH3 and the OH protons may be observed (J = 5.5 Hz).",
    "i": "Pyrrolidine was observed to react with (CD3)2CO.",
    "j": "Acetic anhydride was observed to react with CD3OD and D2O.",
    "k": "Chemical shifts in brackets correspond to −OD isotopomer.",
    "l": "A second set of resonances was observed for anisole in D2O: 6.79, t (J = 7.9 Hz); 6.50−6.43, m; 3.08, s.",
    "m": "Overlapping −OH and −OD isotopomer resonances were observed. ",
    "n": "1:1:1 triplet, JH,D = 0.8 Hz.",
    "o": "Phosphorus coupling was observed (2JP,C = 3 Hz).",
    # ------------------------------------------------------------
}

# Map ref keys -> full bibliographic strings
REFERENCES = {
    # ---- Examples (fill in your actual sources) ----
    "1997": "[1997]: J. Org. Chem. 1997, 62, 21, 7512–7515.",
    "2010": "[2010]: Organometallics 2010, 29, 9, 2176–2179.",
    "2016": "[2016]: Org. Process Res. Dev. 2016, 20, 3, 661–667.",
    # ------------------------------------------------------------
}