# -*- coding: utf-8 -*-
"""__init__

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b9AYTDRBjka4xGow7eMX4L9Pn8LKiKQN
"""

# -*- coding: utf-8 -*-
"""logic package public API

Re-exports commonly used functions and constants so widgets and other modules
can import from `logic` directly (absolute imports), keeping UI and math separated.

Available groups:
- Core formula utilities (from logic/logic.py)
- Physical constants (from logic/constants.py)
- Viscosity model helpers (from logic/viscosity.py)
- DOSY calculations (from logic/dosy.py)
- Dilution & solution preparation (from logic/dilution.py)
"""

# ---- Core formula utilities (parsing, MW, composition, formatting) ----
from .logic import (
    parse_chemical_formula,
    calculate_molecular_weight,
    calculate_elemental_composition,
    merge_formulas,
    format_chemical_formula_html,
    format_composition_string,
    format_nmr_coupling_html,
    format_chemical_inline_html,
    format_notes_richtext_html,
    solvent_sort_key,

)

# ---- Physical constants (CODATA, SEGWE parameters) ----
from .constants import KB, PI, NA, RHO_EFF

# ---- Viscosity model (uses lib.nmr_solvent_data) ----
from .viscosity import viscosity_and_solvent_mw

# ---- DOSY (Stokes–Einstein & SEGWE) ----
from .dosy import (
    se_rh_from_D,
    se_D_from_rh,
    segwe_effective_radius_from_MW,
    segwe_f_gw,
    segwe_D,
    segwe_estimate_MW_from_D,
)

# ---- Dilution & solution preparation ----
from .dilution import (
    volume_of_stock_L,
    mass_for_solution_g,
    stock_molarity_from_density_M,
)

__all__ = [
    # Core formula utilities
    "parse_chemical_formula",
    "calculate_molecular_weight",
    "calculate_elemental_composition",
    "merge_formulas",
    "format_chemical_formula_html",
    "format_composition_string",
    "format_nmr_coupling_html",
    "format_chemical_inline_html",
    "format_notes_richtext_html",
    # Physical constants
    "KB",
    "PI",
    "NA",
    "RHO_EFF",
    # Viscosity
    "viscosity_and_solvent_mw",
    # DOSY
    "se_rh_from_D",
    "se_D_from_rh",
    "segwe_effective_radius_from_MW",
    "segwe_f_gw",
    "segwe_D",
    "segwe_estimate_MW_from_D",
    # Dilution
    "volume_of_stock_L",
    "mass_for_solution_g",
    "stock_molarity_from_density_M",
]