# -*- coding: utf-8 -*-
"""constants

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17DLFG8rBQFyKP6cT5R6yb-vFOsV1gow7
"""

import math

# Fundamental constants (CODATA)
KB: float = 1.380649e-23     # J/K
PI: float = math.pi
NA: float = 6.02214076e23    # mol^-1
RHO_EFF: float = 627.0    # Effective density (kg/m^3) for SEGWE