# -*- coding: utf-8 -*-
"""dilution

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nmxRtQNwfby7fYwOyqndiuU3BcLJSEZd
"""

from typing import Tuple


def volume_of_stock_L(c1_M: float, c2_M: float, v2_L: float) -> float:
    """
    Basic C1 V1 = C2 V2:
        V1 = (C2 * V2) / C1   (liters)
    """
    if c1_M <= 0:
        raise ValueError("Stock concentration (C1) must be > 0.")
    return (c2_M * v2_L) / c1_M


def mass_for_solution_g(mw_g_per_mol: float, conc_M: float, vol_L: float) -> float:
    """
    Mass of solute (g) needed to make 'vol_L' liters at 'conc_M' molarity.
        mass = MW * conc * vol
    """
    if mw_g_per_mol <= 0:
        raise ValueError("Molecular weight must be > 0.")
    return mw_g_per_mol * conc_M * vol_L


def stock_molarity_from_density_M(density_g_per_mL: float, purity_wt_frac: float,
                                  mw_g_per_mol: float) -> float:
    """
    Approximate molarity of a commercial liquid reagent (acids/bases) from:
        density (g/mL), purity (w/w fraction), MW (g/mol)
    Using 1000 mL per liter:
        M ≈ (density * 1000 * purity) / MW
    """
    if mw_g_per_mol <= 0 or density_g_per_mL <= 0 or purity_wt_frac <= 0:
        raise ValueError("MW, density, and purity must be > 0.")
    return (density_g_per_mL * 1000.0 * purity_wt_frac) / mw_g_per_mol