# -*- coding: utf-8 -*-
"""viscosity

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d6sE-Uaz7QQxdADh1yCyE_2Qnd6l0GRm
"""

from typing import Tuple, Optional
import math
from lib import nmr_solvent_data


def viscosity_and_solvent_mw(solvent: str, T: float) -> Tuple[Optional[float], Optional[float]]:
    """
    Return (eta_Pa_s, solvent_MW_g_per_mol) for a given solvent at temperature T (K).
    Supports 'direct' and 'inferred' entries from lib.nmr_solvent_data
    """
    data = nmr_solvent_data.SOLVENT_DATA.get(solvent)
    if not data:
        return None, None

    typ = data.get("type")
    if typ == "direct":
        a = data["a"]
        b = data["b"]
        mw = data["mw"]
        eta = a * math.exp(b / T)
        return eta, mw

    if typ == "inferred":
        ref_name = data["ref"]
        ref = nmr_solvent_data.NON_DEUTERATED_REFS.get(ref_name)
        if not ref:
            return None, None
        eta_h = ref["a"] * math.exp(ref["b"] / T)
        eta_d = eta_h * (data["mw_d"] / ref["mw"])
        return eta_d, data["mw_d"]

    if typ == "custom":
        # Caller is expected to provide manual values in the UI; we return (None, None)
        return None, None